### PR TITLE
[orchagent] PFC WD support for BFN platform

### PR DESCRIPTION
**Pull request by vsenchyshyn**
**What I did**
This is a clone of this PR: https://github.com/Azure/sonic-swss/pull/823 for 201811

**Why I did it**

**How I verified it**
pfc_wd community test on barefoot platform passed.

**Details if related**

### CODE REVIEW

**Comment by vsenchyshyn** [comment]
@lguohan @wendani Please review.

**Comment by wendani** [comment]
@vsenchyshyn add a comment "retest this please" can trigger a new build and test chain. We do not need to create a new pr

**Comment by vsenchyshyn** [comment]
> @vsenchyshyn add a comment "retest this please" can trigger a new build and test chain. We do not need to create a new pr

Wow interesting trick! Thanks a bunch!

**Comment by wendani** [comment]
Also you do not need to create a pr specifically for 20181130 image. There is a label in the label section called "include in 20181130 image".  Just add it to your original pr to mark the necessity for 1130 inclusive. Maintainer will pick it up later once it is merged to master

**Comment by vsenchyshyn** [comment]
> could you correct the commit title name to orchagent?

Done!

**Pull request merged**
