### PR TITLE
packaging: Move common and tests to sonic-common repo

### PR DESCRIPTION
**Pull request by stcheng**
This pull request will remove common and test folder from the swss repo and they will be put into a new repo: https://github.com/Azure/sonic-swss-common.

This will solve the circulated dependency between swss/libswsscommon/sairedis.

Feel free to leave comments here.

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

### CODE REVIEW

**Comment by eladraz** [comment]
Please do "git remote add" to sonic-swss-common and apply git history.

**Comment by stcheng** [comment]
Please take a look at my fork see if it has the right git history: https://github.com/stcheng/sonic-swss-common

**Comment by eladraz** [comment]
Acked-by: Elad Raz <eladr@mellanox.com>

**Comment by stcheng** [comment]
thanks

**Pull request closed without merging**
