### PR TITLE
[202012][PFCWD + Asym PFC]: Allow PFCWD to detect PFC storm on all pr…

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
…iorities when Asym PFC is enabled

Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>

Same as https://github.com/Azure/sonic-swss/pull/1360 but for 202012 since cherry-pick has merge conflicts

**What I did**
Add possibility for PFCWD  to detect PFC storm on all priorities when asymmetric PFC is enabled.

According to requirements PFCWD should detect PFC storm on the lossy priorities for the port on which asymmetric PFC is enabled.
(when asymmetric PFC is enabled on some port that means such port is enabled for receiving PFC frames on all priorities)

**Why I did it**
To fix issue https://github.com/Azure/sonic-swss/issues/1128.

**How I verified it**
1. Enable asymmetric PFC on test port.
```
pfc config asymmetric on <port>
```
2. Enable PFCWD on the test port.
```
pfcwd start --action drop --restoration-time 3000 <port> 1000
pfcwd interval 500
```
3. Run ```pause``` frames to the test port for all priorities.
4. Verify that PFCWD detected storm for all priorities.
```
pfcwd show stats
```

**Details if related**
N/A

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@volodymyrsamotiy can you please handle LGTM error?

**Comment by liat-grozovik** [comment]
@volodymyrsamotiy  please check LGTM failure and handle

**Comment by volodymyrsamotiy** [comment]
> @volodymyrsamotiy please check LGTM failure and handle

It is not related to my changes.
It looks like something generic and related to build infra:
```
[2021-08-26 09:01:54] [build-stderr] main.cpp:2:10: fatal error: sai.h: No such file or directory
[2021-08-26 09:01:54] [build-stderr]     2 | #include "sai.h"
[2021-08-26 09:01:54] [build-stderr]       |          ^~~~~~~
[2021-08-26 09:01:54] [build-stderr] compilation terminated.
[2021-08-26 09:01:54] [build-stdout] make[2]: Leaving directory '/opt/src/orchagent'
[2021-08-26 09:01:54] [build-stderr] make[2]: *** [Makefile:623: orchagent-main.o] Error 1
```

**Comment by liat-grozovik** [comment]
@qiluo-msft do you have an idea how to overcome it?

**Comment by liat-grozovik** [comment]
@neethajohn could you please help to merge regardless of the LGM issue or you can suggest how to overcome it?

**Comment by liat-grozovik** [comment]
@volodymyrsamotiy  it seems lgtm is not working also on 201911. please see https://github.com/Azure/sonic-swss/pull/1901

**Comment by liat-grozovik** [comment]
@neethajohn kindly reminder for the review

**Comment by qiluo-msft** [comment]
Please resolve the conflicts.

**Comment by liat-grozovik** [comment]
@neethajohn could you please help to review?

**Pull request closed without merging**
