### PR TITLE
[Overlay] Add BGP profile to Vnet routes

### PR DESCRIPTION
**Pull request by prsunny**
**What I did**
Add BGP profile support to Vnet routes

**Why I did it**
If a profile is specified in Vnet routes, it must be reflected in the STATE_DB routes for advertising:

```
HGETALL "ADVERTISE_NETWORK_TABLE|150.62.192.1/32"
1) "profile"
2) "FROM_SLB_ROUTES"
```

**How I verified it**
With VS tests

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@StormLiangMS for viz

**Review by sumukhatv — APPROVED** [review]

**Pull request merged**
