### PR TITLE
[202111] [FDB] Fix fbdorch to properly handle syncd FDB FLUSH Notif

### PR DESCRIPTION
**Pull request by vivekreddynv**
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

**What I did**

Backport https://github.com/Azure/sonic-swss/pull/2254

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
the failure is a result of timeout. restarting now. but if issue reproduce suggest to discuss with buidl team

**Comment by liat-grozovik** [comment]
@vivekreddynv  could you pls check the failures and see if need to rebase or a fix is missing

**Comment by vivekreddynv** [comment]
> @vivekreddynv could you pls check the failures and see if need to rebase or a fix is missing

test_removebufferpool is failing. This PR must be backported to 202111 https://github.com/Azure/sonic-swss/pull/2269

**Comment by liat-grozovik** [comment]
@vivekreddynv  please check failures

**Pull request merged**
