### PR TITLE
[orchagent] Increase SAI REDIS response timeout to support FW upgrade during init (Mellanox only)

### PR DESCRIPTION
**Pull request by liorghub**
Increase orchagent SAI REDIS response timeout to support FW upgrade during init (Mellanox only).
This change should be merged after the following PRs were merged:
Azure/sonic-sairedis#774

Signed-off-by: liora <liora@nvidia.com>

**What I did**
Increase orchagent SAI REDIS response timeout during init in order for orchagent to wait enough time for response from syncd since in init, syncd startup script first calls FW upgrade script (that might take up to 7 minutes in systems with Gearbox) and only then launches syncd.

**Why I did it**
To support FW upgrade during init flow.

**How I verified it**
I manually changed ASIC and Gearbox FW followed by hard reset in order for FW upgrade to take place on init.

**Which release branch to backport**
- [x] 202012

### CODE REVIEW

**Comment by liorghub** [comment]
@liat-grozovik Looks like build environment issue, can you re run please?

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by kcudnik** [comment]
retest vs please

**Comment by liorghub** [comment]
@kcudnik @liat-grozovik 

ARM build is failing. 
Unfortunately I couldn’t find the root cause in log, however I noticed a gap of 30 seconds in log (see below).

2021-02-16T20:58:03.3481304Z     __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,
2021-02-16T20:58:33.9199964Z make[3]: Leaving directory '/__w/2/s/orchagent'

Did you see it before? 
Maybe rerun will help?

**Comment by kcudnik** [comment]
im looking to some recent build like this: https://github.com/Azure/sonic-swss/pull/1643, all checks are passing, and i see a lot of similar warnings during compilation: https://dev.azure.com/mssonic/build/_build/results?buildId=4187&view=logs&jobId=e51ebb60-45fa-5846-0822-3aaf597a9c80&j=e51ebb60-45fa-5846-0822-3aaf597a9c80&t=22830a29-09d4-5764-f143-c6b729e2f8db which takes over 2h but completes fine

as for your actual error comes from here:
```
021-02-16T20:53:58.7599011Z In file included from saihelper.cpp:12:
2021-02-16T20:53:58.7600911Z saihelper.cpp: In function 'void initSaiRedis(const string&, const string&)':
2021-02-16T20:53:58.7602862Z /usr/include/swss/logger.h:17:101: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'sai_uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
2021-02-16T20:53:58.7605002Z  #define SWSS_LOG_NOTICE(MSG, ...)      swss::Logger::getInstance().write(swss::Logger::SWSS_NOTICE, ":- %s: " MSG, __FUNCTION__, ##__VA_ARGS__)
2021-02-16T20:53:58.7606582Z saihelper.cpp:300:9: note: in expansion of macro 'SWSS_LOG_NOTICE'
2021-02-16T20:53:58.7607669Z          SWSS_LOG_NOTICE("SAI REDIS response timeout set successfully to %lu", attr.value.u64);
2021-02-16T20:53:58.7608412Z          ^~~~~~~~~~~~~~~
2021-02-16T20:53:58.7716910Z /usr/include/swss/logger.h:17:101: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'sai_uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
2021-02-16T20:53:58.7718978Z  #define SWSS_LOG_NOTICE(MSG, ...)      swss::Logger::getInstance().write(swss::Logger::SWSS_NOTICE, ":- %s: " MSG, __FUNCTION__, ##__VA_ARGS__)
2021-02-16T20:53:58.7721025Z saihelper.cpp:327:9: note: in expansion of macro 'SWSS_LOG_NOTICE'
2021-02-16T20:53:58.7721824Z          SWSS_LOG_NOTICE("SAI REDIS response timeout set successfully to %lu", attr.value.u64);
2021-02-16T20:53:58.7722503Z          ^~~~~~~~~~~~~~~
```

for cross arm compilation you need to use PRIu64 prefixes instead of "%lu"

as for warning described here: https://stackoverflow.com/questions/48149323/what-does-the-gcc-warning-project-parameter-passing-for-x-changed-in-gcc-7-1-m
i think we can pass "-Wno-psabi" on arm to not pollute compilation logs to better see whats heppening

**Comment by liorghub** [comment]
@kcudnik Kamil thank you so much, I fixed the PRIu64 thing.
Actually I also looked on other logs that passed and saw all the warnings but those are not failing the compilation and I have no masochistic desires to add changes in build system :)

Can you please rerun for me?

**Comment by liorghub** [comment]
@kcudnik Please merge and backport  to 202012. 
I verified clean cherry-pick. I also verified that related commits are already there.

**Review by kcudnik — APPROVED** [review]

**Comment by dprital** [comment]
Hi @kcudnik - can you please merge it and also backport to 202012 ?

**Comment by liorghub** [comment]
@liat-grozovik  can you please add backport to 202012 tag?

**Comment by liat-grozovik** [comment]
no i cannot. 
@daall  your help is needed. I cannot add the label to this repository.

**Comment by liorghub** [comment]
@yxieca Hello Ying, I couldn't find this commit in swss 202012, please advise.

**Comment by yxieca** [comment]
@liorghub the submodule update PR just got merged. You should be able to see it now.

**Pull request merged**
