### PR TITLE
[vlan] Add pytest case to add max vlan.

### PR DESCRIPTION
**Pull request by linemma**
**What I did**
[vlan] Add pytest cases to add max vlan.

**Why I did it**

**How I verified it**
Add test case:
1. Add max vlan (2-4094) and remove it. => succeed

**Details if related**
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: /home/ubuntu/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 25 items

test_vlan.py::TestVlan::test_VlanAddRemove PASSED 										[  4%]
test_vlan.py::TestVlan::test_MultipleVlan PASSED										[  8%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input0-0] PASSED		[ 12%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input1-0] PASSED		[ 16%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input2-0] PASSED		[ 20%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input3-1] PASSED		[ 24%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input0-0] PASSED		[ 28%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input1-0] PASSED		[ 32%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input2-0] PASSED		[ 36%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input3-1] PASSED		[ 40%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectKeyPrefix[test_input0-0] PASSED	[ 44%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectKeyPrefix[test_input1-0] PASSED	[ 48%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectKeyPrefix[test_input2-0] PASSED	[ 52%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectValueType[test_input0-0] PASSED	[ 56%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectValueType[test_input1-0] PASSED	[ 60%]
test_vlan.py::TestVlan::test_AddVlanMemberWithIncorrectValueType[test_input2-0] PASSED	[ 64%]
test_vlan.py::TestVlan::test_VlanMemberTaggingMode[test_input0-expected0] PASSED		[ 68%]
test_vlan.py::TestVlan::test_VlanMemberTaggingMode[test_input1-expected1] PASSED		[ 72%]
test_vlan.py::TestVlan::test_VlanMemberTaggingMode[test_input2-expected2] PASSED		[ 76%]
test_vlan.py::TestVlan::test_VlanMemberTaggingMode[test_input3-expected3] PASSED		[ 80%]
test_vlan.py::TestVlan::test_VlanMemberTaggingMode[test_input4-expected4] PASSED		[ 84%]
test_vlan.py::TestVlan::test_AddVlanMemberWithNonExistVlan PASSED						[ 88%]
test_vlan.py::TestVlan::test_RemoveNonexistentVlan PASSED								[ 92%]
test_vlan.py::TestVlan::test_AddPortChannelToVlan PASSED								[ 96%]
test_vlan.py::TestVlan::test_AddMaxVlan PASSED 											[100%]

================================================================= 25 passed in 453.56 seconds =================================================================

Signed-off-by: Emma Lin <emma_lin@edge-core.com>

### CODE REVIEW

**Comment by stcheng** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by linemma** [comment]
The original author information is incorrect, so I just modify it at dbcd020.

**Comment by stcheng** [comment]
@linemma why the total time for running this test only costed 453.56 seconds ?

we have sleep(1) for both create/remove vlan, if there're 4k vlans, the total time shall be different.

**Comment by linemma** [comment]
@stcheng sorry, I forgot to update the test time on final version. 453.56 seconds is the test time on first commit.

At first commit, I add an option parameter in create_vlan and remove_vlan to skip sleep to run test_AddMaxVlan. And after creating or removing vlan, call time.sleep to wait some time.

```
        # create max vlan
        vlan = min_vid
        while vlan <= max_vid:
            self.create_vlan(str(vlan), 0)
            vlan += 1
        time.sleep(150)

        # remove all vlan
        vlan = min_vid
        while vlan <= max_vid:
            self.remove_vlan(str(vlan), 0)
            vlan += 1
        time.sleep(200)
```

But the sleep time seems not enough on Jenkins. So I modify the sleep code to original behavior.

**Pull request merged**
