### PR TITLE
[vlan] Add pytest cases to validate the behavior about add LAG member to vlan.

### PR DESCRIPTION
**Pull request by linemma**
**What I did**
[vlan] Add pytest cases to validate the behavior about add LAG member to vlan.

**Why I did it**

**How I verified it**
Add test case:
1. Add LAG member to vlan and remove it. => succeed

**Details if related**
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: /home/ubuntu/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 11 items

test_vlan.py::TestVlan::test_VlanAddRemove PASSED 									[  9%]
test_vlan.py::TestVlan::test_MultipleVlan PASSED 									[ 18%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input0-0] PASSED 	[ 27%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input1-0] PASSED 	[ 36%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input2-0] PASSED 	[ 45%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input3-1] PASSED 	[ 54%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input0-0] PASSED 	[ 63%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input1-0] PASSED 	[ 72%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input2-0] PASSED 	[ 81%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input3-1] PASSED 	[ 90%]
test_vlan.py::TestVlan::test_AddPortChannelToVlan PASSED 							[100%]

================================================================= 11 passed in 62.15 seconds =================================================================

Signed-off-by: Emma Lin <emma_lin@edge-core.com>

### CODE REVIEW

**Comment by linemma** [comment]
I check the test results, the test failed is caused by warm reboot case:
test_warm_reboot.py::test_system_warmreboot_neighbor_syncup FAILED       [ 97%]
============== 1 failed, 112 passed, 7 skipped in 6416.11 seconds ==============

The test case was PASSED on 1st commit of this PR, but failed on 2nd commit. I did not modify any warm reboot pytest codes on 2nd commit. Could someone kindly tell me how to pass the case? Thanks a lot.

**Comment by linemma** [comment]
retest this please

**Comment by lguohan** [comment]
@linemma , can you resolve the conflict?

**Comment by linemma** [comment]
@lguohan resolved, please review again. Thanks.

**Comment by linemma** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by lguohan** [comment]
need to resolve the conflict again due to previous vlan test contribution from you.

**Comment by linemma** [comment]
@lguohan, resolved, please review again. Thanks!

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Pull request merged**
