### PR TITLE
Add scope attribute to VNET table.

### PR DESCRIPTION
**Pull request by prsunny**
**What I did**
Add a global `scope ` to VNET to consider default VRF

**Why I did it**
Currently, for every VNET table, a new Virtual Router is created in ASIC. This is a special use-case where the encap/decap is expected to happen in the `default `Virtual Router. 

**How I verified it**
VS test

**Details if related**

### CODE REVIEW

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
retest vs please

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Pull request merged**
