### PR TITLE
[VS] Skip consistently failing test cases

### PR DESCRIPTION
**Pull request by prsunny**
**What I did**
The following two tests are consistently failing. Skipping for investigation:

```
test_changeCableLen
test_AddTwiceNatEntry
```

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@neethajohn for viz

**Comment by neethajohn** [comment]
@stephenxs , test_changeCableLen failures

**Review by neethajohn — APPROVED** [review]

**Comment by prsunny** [comment]
@stephenxs , please check this build for reference - https://dev.azure.com/mssonic/build/_build/results?buildId=72704&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5

**Review by qiluo-msft — APPROVED** [review]

**Comment by prsunny** [comment]
All tests passed - https://dev.azure.com/mssonic/build/_build/results?buildId=72878&view=results

**Comment by stephenxs** [comment]
> @stephenxs , please check this build for reference - https://dev.azure.com/mssonic/build/_build/results?buildId=72704&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5

thanks. will check and fix it.

**Pull request merged**
