### PR TITLE
Use .clear() after std::move()

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**What I did**
1. Use .clear() on a vector after using std::move() from it to make sure that the vector is in a correct state.
2. Remove the if condition which is not required here.

**Why I did it**
1. std::move() from an object leaves the object in correct state. The correct state could be not empty. So I clear the vector to make sure that the vector is empty.
2. We don't need to check the vector on the emptiness. The for loop will do nothing, if there is no elements in the vector.

**How I verified it**
Make a draft PR and wait to make sure that there is no regression.

**Details if related**

### CODE REVIEW

**Comment by wendani** [comment]
👍

**Comment by pavel-shirshov** [comment]
retest all please

**Comment by pavel-shirshov** [comment]
retest this please

**Comment by pavel-shirshov** [comment]
retest vs please

**Review by prsunny — APPROVED** [review]

**Pull request merged**
