### PR TITLE
Enable MIRRORv6 for BFN platform

### PR DESCRIPTION
**Pull request by msosyak**
**What I did**
Add MIRRORv6 support for Barefoot platform

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by akokhan** [comment]
retest vs please

**Comment by msosyak** [comment]
retest vs please

**Comment by msosyak** [comment]
retest this please

**Comment by msosyak** [comment]
@lguohan Looks loke vs check is broken. Could you merge this without check pass, ss there are only BFN specific changes

**Comment by msosyak** [comment]
retest this please

**Comment by msosyak** [comment]
retest this please

**Comment by msosyak** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by msosyak** [comment]
retest this please

**Pull request merged**
