### PR TITLE
[vnet]: Extend Bitmap VNET test with "remove" flows

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**What I did**
Extended Bitmap VNET virtual switch test with "remove" flows
**Why I did it**
In order to test Bitmap VNET remove flows
**How I verified it**
Executed VNET test and verified it passed
**Details if related**
N/A

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
retest this please

**Pull request merged**
