### PR TITLE
[crm] Use sai_object_type_get_availability() API to get counters

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>

**What I did**
Aligned supported CRM resources with the newest way to get counters using sai_object_type_get_availability() API.

**Why I did it**
To use newest way to get CRM counters

**How I verified it**
Run CRM test from sonic-mgmt 

**Details if related**
N/A

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@prsunny while you are reviewing this change, please consider adding it to 202111 and add the right label.

**Comment by liat-grozovik** [comment]
@prsunny  kindly reminder to review and signoff
please note that the LTGM issue seen on other PRs also seen here. I suggest to take further look as it seems like SAI/sairedis issue.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
