### PR TITLE
Temporarily disable Acl thread to collect counters

### PR DESCRIPTION
**Pull request by qiluo-msft**
In order to mitigate https://github.com/Azure/sonic-swss/issues/201

### CODE REVIEW

**Comment by stcheng** [comment]
there are some issues with the build due to the previous checked in code https://github.com/Azure/sonic-sairedis/pull/178. resolve the build issue first and then merge this commit.

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
does the acl test reads any acl counters?

**Comment by stcheng** [comment]
Yes. Some of the ACL test reads the ACL counters.

**Comment by lguohan** [comment]
I guess we have to disable the acl thread right now, you probably need a local version to keep the acl test running.

**Pull request merged**
