### PR TITLE
Correct the sflow default sample rate

### PR DESCRIPTION
**Pull request by fredyu190011**
**What I did**
Correct the sflow default sample rate to "ifSpeed / 1e6".

**Why I did it**
According the PR: [SONiC#746](https://github.com/Azure/SONiC/pull/746), the sample rate should be "ifSpeed / 1e6".

**How I verified it**

**Details if related**
Signed-off-by: Fred Yu fred_yu@edge-core.com

### CODE REVIEW

**Comment by prsunny** [comment]
@dgsudharsan , @padmanarayana to review

**Review by dgsudharsan — DISMISSED** [review]

**Review by padmanarayana — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Review by padmanarayana — DISMISSED** [review]

**Comment by prsunny** [comment]
@fredyu190011 , can you please do a force-push?

**Comment by fredyu190011** [comment]
Hi @prsunny , I solve the conflict through merge. Is it okay?

**Comment by dgsudharsan** [comment]
@fredyu190011 Please address my latest comments.

**Comment by fredyu190011** [comment]
Hi @dgsudharsan , I cannot see your latest comment.
I fixed some merging mistake to pass the auto test.

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@prsunny Can we merge this?

**Comment by dgsudharsan** [comment]
Please add it for 202012 branch.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
