### PR TITLE
[flex-counters] [202012] Delay flex counters stats init for faster boot time

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**What I did**
Update flex counters DB with counters stats only when counters are enabled.
As long as the polling counters are not enabled, flex counters information will stored internally on PortsOrch.

**Why I did it**
Creating flex counters objects on the DB will trigger 'SYNCD' to access the HW for query statistics capabilities.
This HW access takes time and will be better to finish boot before doing this (mainly for fast-reboot but good to have in general).
The flex counters are not crucial at boot time, we can delay it to the end of the boot process.

**How I verified it**
Reboot a switch and observer the flex counters DB populated after counters are enabled.

**Details if related**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@tahmed-dev and @qiluo-msft we believe this can improve performance for any boot but specially for fastboot.
Can you please review and provide your feedback?

**Comment by liat-grozovik** [comment]
@qiluo-msft kindly reminder. we need the fix merged in order to test fastboot and get some improvements.

**Comment by qiluo-msft** [comment]
Please update this PR according to the iterations in https://github.com/Azure/sonic-swss/pull/1749

**Comment by qiluo-msft** [comment]
Can we cleanly cherry-pick https://github.com/Azure/sonic-swss/pull/1749?

**Comment by shlomibitton** [comment]
@qiluo-msft fixed the PR according to the comments on master.
Previously I tried to cherry-pick and it didn't apply cleanly, this is why I created this additional PR.

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Close this one because the master branch PR https://github.com/Azure/sonic-swss/pull/1749 was reverted.
You can reopen if you want to update with new solution.

**Pull request closed without merging**
