### PR TITLE
[aclorch]: Allow DTEL drop actions in DTEL flow watchlist

### PR DESCRIPTION
**Pull request by mickeyspiegel**
In order to simplify operations, it may be desirable to combine the
DTEL flow and drop watchlists into one single watchlist that contains
both flow and drop actions. This change adds the drop actions to the
flow watchlist, allowing the combination of flow and drop actions in
a single ACL table.

This change also allows ACTION_DTEL_REPORT_ALL_PACKETS in drop
watchlists.

Signed-off-by: Mickey Spiegel <mspiegel@barefootnetworks.com>

**What I did**
This change adds the drop actions to the flow watchlist, allowing the combination of flow and drop actions in a single ACL table.
This change also allows ACTION_DTEL_REPORT_ALL_PACKETS in drop watchlists.

**Why I did it**
In order to simplify operations, it may be desirable to combine the DTEL flow and drop watchlists into one single watchlist that contains both flow and drop actions.

**How I verified it**
Tested on a Barefoot switch, showing that an ACL entry can be created with the combined watch flow and drops action. Verified that the hardware was programmed with the combined action. Verified that both DTEL flow and drop reports are generated for packets matching the ACL entry.

**Details if related**

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by mickeyspiegel** [comment]
Please add this to the 201811 branch as well as master

**Comment by stcheng** [comment]
retest this please

**Comment by lguohan** [comment]
Retest this please

**Pull request merged**
