### PR TITLE
[rates] fix undefined var in lua scripts

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

**What I did**
Fixed some minor issueswith lua scripts:
 - undefined variables
 - typo
**Why I did it**

**How I verified it**
`redis-cli --eval port_rates.lua ,`
observe no error
**Details if related**

### CODE REVIEW

**Comment by kcudnik** [comment]
currently on master sonic build image we get this error:
ERR syncd#syncd: :- guard: RedisReply catches system_error: command: *39#015#012$7#015#012EVALSHA#015#012$40#015#01231fc701ca9b1b9f968f501c92b639f50f6346a9c#015#012$2#015#01232#015#012$19#015#012oid:0x1000000000002#015#012$19#015#012oid:0x1000000000003#015#012$19#015#012oid:0x1000000000004#015#012$19#015#012oid:0x1000000000005#015#012$19#015#012oid:0x1000000000006#015#012$19#015#012oid:0x1000000000007#015#012$19#015#012oid:0x1000000000008#015#012$19#015#012oid:0x1000000000009#015#012$19#015#012oid:0x100000000000a#015#012$19#015#012oid:0x100000000000b#015#012$19#015#012oid:0x100000000000c#015#012$19#015#012oid:0x100000000000d#015#012$19#015#012oid:0x100000000000e#015#012$19#015#012oid:0x100000000000f#015#012$19#015#012oid:0x1000000000010#015#012$19#015#012oid:0x1000000000011#015#012$19#015#012oid:0x1000000000012#015#012$19#015#012oid:0x1000000000013#015#012$19#015#012oid:0x1000000000014#015#012$19#015#012oid:0x1000000000015#015#012$19#015#012oid:0x1000000000016#015#012$19#015#012oid:0x1000000000017#015#012$19#015#012oid:0x1000000000018#015#012$19#015#012oid:0x1000000000019#015#012$19#015#012oid:0x100000000001a#015#012$19#015#012oid:0x100000000001b#015#012$19#015#012oid:0x100000000001c#015#012$19#015#012oid:0x100000000001d#015#012$19#015#012oid:0x100000000001e#015#012$19#015#012oid:0x100000000001f#015#012$19#015#012oid:0x1000000000020#015#012$19#015#012oid:0x1000000000021#015#012$1#015#0122#015#012$8#015#012COUNTERS#015#012$7#015#0121000000#015#012$2#015#012''#015#012, reason: ERR Error running script (call to f_31fc701ca9b1b9f968f501c92b639f50f6346a9c): @user_script:21: user_script:21: attempt to perform arithmetic on local 'alpha' (a boolean value) : Input/output error

hash f_31fc701ca9b1b9f968f501c92b639f50f6346a9c corrensponds to port_rates.lua script (local variable 'alpha') is this PR fix to fix this issue ? or some other issue ?

**Comment by lguohan** [comment]
does this one fix #1361  ?

**Comment by judyjoseph** [comment]
retest this please

**Comment by mykolaf** [comment]
> does this one fix #1361 ?

https://github.com/Azure/sonic-buildimage/pull/5048 fixes #1361

**Comment by liat-grozovik** [comment]
retest this please

**Comment by lguohan** [comment]
then what issue this one fix? can you add more description?

**Comment by liat-grozovik** [comment]
retest this please

**Pull request merged**
