### PR TITLE
[portsyncd] when no ports on config db on init - continue and set PortConfigDone

### PR DESCRIPTION
**Pull request by tomer-israel**
Signed-off-by: tomeri <tomeri@nvidia.com>

**What I did**
- continue the execution of handlePortConfigFromConfigDB when no ports on config db -> continue and set PortConfigDone
- function handlePortConfigFromConfigDB is no longer boolean - change it to void

**Why I did it**
when there are no ports on config db the PortConfigDone on APP db wasn't set and dynamic add/remove of ports after init stage is damaged.

**How I verified it**
started with no ports configured and verified that PortConfigDone is set on APP db

**Details if related**

### CODE REVIEW

**Comment by tomer-israel** [comment]
i have these failures on the swss checkers:
test_zero_cable_len_profile_update
test_route_nhg
test_route_nhg_exhaust
test_SpeedAndBufferSet

vs tests:
test_SpeedAndBufferSet failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	Unexpected number of keys: expected=4, received=3 (('egress_lossy_profile', 'egress_lossless_profile', 'ingress_lossy_profile')), table="BUFFER_PROFILE"
	[<TracebackEntry /home/vsts/work/1/s/tests/test_speed.py:39>, <TracebackEntry /home/vsts/work/1/s/tests/dvslib/dvs_database.py:366>]
test_SpeedAndBufferSet failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	Unexpected number of keys: expected=4, received=3 (('egress_lossy_profile', 'egress_lossless_profile', 'ingress_lossy_profile')), table="BUFFER_PROFILE"
	[<TracebackEntry /home/vsts/work/1/s/tests/test_speed.py:39>, <TracebackEntry /home/vsts/work/1/s/tests/dvslib/dvs_database.py:366>]

it looks not related to my change and I also saw the same errors on this PR (the PR is not related to our PR):
https://github.com/Azure/sonic-swss/pull/1860

so maybe we need to rerun these tests

**Comment by tomer-israel** [comment]
the code changes are not related to the failures at all:
```

test_dependency failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	Unexpected number of keys: expected=0, received=1 (('oid:0x20000000005e8',)), table="ASIC_STATE:SAI_OBJECT_TYPE_LAG"
	[<TracebackEntry /home/vsts/work/1/s/tests/test_port_dpb_lag.py:55>, <TracebackEntry /home/vsts/work/1/s/tests/dvslib/dvs_lag.py:28>, <TracebackEntry /home/vsts/work/1/s/tests/dvslib/dvs_database.py:366>]

self = <test_port_dpb_lag.TestPortDPBLag object at 0x7f5a632cf550>
dvs = <conftest.DockerVirtualSwitch object at 0x7f5a638cb100>
marker = '=== start marker 2021-08-17T16:31:14.419203 ==='
log = 'Unable to remove port Ethernet0: ref count 1', expected_cnt = 1

    def check_syslog(self, dvs, marker, log, expected_cnt):
        (exitcode, num) = dvs.runcmd(['sh', '-c', "awk \'/%s/,ENDFILE {print;}\' /var/log/syslog | grep \"%s\" | wc -l" % (marker, log)])
>       assert num.strip() >= str(expected_cnt)
E       AssertionError: assert '0' >= '1'
E        +  where '0' = <built-in method strip of str object at 0x7f5a63a6c7f0>()
E        +    where <built-in method strip of str object at 0x7f5a63a6c7f0> = '0\n'.strip
E        +  and   '1' = str(1)

test_port_dpb_lag.py:11: AssertionError

```
my changes are related to init stage only when we are starting the system with zero ports, we continue to send portConfigDone

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prsunny could you please help to review and merge?

**Comment by prsunny** [comment]
How is this different from https://github.com/Azure/sonic-swss/pull/1808 ?

**Comment by tomer-israel** [comment]
> How is this different from #1808 ?

in this change the function "handlePortConfigFromConfigDB" is continuing when we have no ports on the system and the PortConfigDone flag is set on App db

**Comment by liat-grozovik** [comment]
@prsunny  can you please signoff?

**Pull request merged**
