### PR TITLE
Setup ip2me trap for netdev channel

### PR DESCRIPTION
**Pull request by garyachy**

### CODE REVIEW

**Comment by garyachy** [comment]
@stcheng  pls. review

**Comment by stcheng** [comment]
@garyachy This part of code will later be removed because we're using COPP and config file to configure the trap groups and use IP2Me route to trap packets coming to the switch.

**Comment by stcheng** [comment]
Thanks.

**Comment by garyachy** [comment]
@stcheng I am aware of copp configuration file but do not agree with closing the PR

**Comment by stcheng** [comment]
@garyachy After using the COPP config file, this whole part of code will be removed.

**Comment by garyachy** [comment]
@stcheng I understand that. But you reverted it on some purpose, right?

**Comment by stcheng** [comment]
@garyachy I reverted that because at that time the COPP sample configuration was not yet done. I'll remove it as soon as I verified that the COPP config works.

**Pull request closed without merging**
