### PR TITLE
[everflow/acl]: Allow to create mirror ACL rules in L3 table.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**

### CODE REVIEW

**Comment by lguohan** [comment]
can you update the scheme as well?

**Comment by oleksandrivantsiv** [comment]
@lguohan Schema didn't changed. I've removed restriction that denied to create rules with mirror action in L3 table. But this restriction wasn't described in schema.

**Comment by lguohan** [comment]
there is 

"mirror_action = 1*255VCHAR                 ; refer to the mirror session
                                           ; (only available to mirror acl
                                           ; table type)
"

**Comment by oleksandrivantsiv** [comment]
@lguohan done

**Comment by stcheng** [comment]
Thanks

**Pull request merged**
