### PR TITLE
configure extra inc/lib directory for build

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <lguohan@gmail.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by lguohan** [comment]
to enable LGTM

**Comment by qiluo-msft** [comment]
Can we see LGTM C++ results in this PR's checker?

**Comment by lguohan** [comment]
> Can we see LGTM C++ results in this PR's checker?

not until you have merged.

**Comment by lguohan** [comment]
here is the current build. https://lgtm.com/projects/g/Azure/sonic-swss/logs/languages/lang:cpp

We have to first enable the build to be successful, then we can see the analysis results. This pr is just to make neccessary change so that we can build the project successfully in the lgtm enviroment.

**Comment by stephenxs** [comment]
@lguohan @qiluo-msft as we have enabled LGTM on 201911, we need this PG as well. Can you help cherry pick it to 201911?

**Comment by qiluo-msft** [comment]
@abdosi Could you help cherry-pick to 201911?

**Pull request merged**
