### PR TITLE
Completely remove "recirc port" code

### PR DESCRIPTION
**Pull request by qiluo-msft**
**What I did**
Completely remove "recirc port" code. The intention of 1813 is to revert 1530, but it is not complete.
Reverts below commits
```
7c7c4513 2021-07-06 | Revert recirc port change (#1813) [Song Yuan]
5ef4b382 2021-06-01 | Add support for recirc port and everflow (#1530) [Song Yuan]
```

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@ysmanman Could you also help review?

**Comment by prsunny** [comment]
@kcudnik for viz

**Review by prsunny — APPROVED** [review]

**Comment by kcudnik** [comment]
Address lgtm alerts ? also will this be back, since it seems more right to find root cause of this and fix it instead of remove it completely

**Comment by qiluo-msft** [comment]
LGTM result is actually positive, fixing 2.
Not sure about the feature itself. I am following the PR owner's intention in #1813.

**Comment by ysmanman** [comment]
Why do we want to revert this change? This will break everflow support.

**Comment by abdosi** [comment]
@qiluo-msft why we are reverting ? Idea of PR https://github.com/Azure/sonic-swss/pull/1813 was to revert code that was needed when SAI did not have  correct support so when SAI has correct support this PR reverted it.

**Review by abdosi — CHANGES_REQUESTED** [review]
Need clarification why PR needs revert ?

**Pull request closed without merging**
