### PR TITLE
[Reclaiming buffer][202106] Support reclaiming buffer in traditional model

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**
It's to port #2011 to 202106
To reclaim reserved buffer.
As the way to do it differs among vendors, `buffermgrd` will:

- Handle port admin down on Mellanox platform.
  - Not apply lossless buffer PG to an admin-down port 
  - Remove lossless buffer PG (3-4) from a port when it is shut down.
- Readd lossless buffer PG (3-4) to a port when a port is started up.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**
To support reclaiming reserved buffer when a port is shut down on Mellanox platform in traditional buffer model.

**How I verified it**

Regression test and vs test.

**Details if related**

### CODE REVIEW

**Comment by stephenxs** [comment]
It can be cherry-picked to 202012 branch (commit e37302d8096b06d49c37e9c4062d180fc4d752e1) cleanly, so tag added.

**Comment by neethajohn** [comment]
@prsunny , do we do such kind of cherry-picks? from non master branch?

**Review by neethajohn — APPROVED** [review]

**Comment by prsunny** [comment]
agree with Neetha. typically we don't follow this model. if it cannot be cherry-picked from master, please raise separate PRs to dev branches.

**Comment by stephenxs** [comment]
> agree with Neetha. typically we don't follow this model. if it cannot be cherry-picked from master, please raise separate PRs to release branches.

Thanks for clarifying it. Will open another PR for 202012. Thanks.

**Comment by stephenxs** [comment]
> > agree with Neetha. typically we don't follow this model. if it cannot be cherry-picked from master, please raise separate PRs to release branches.
> 
> Thanks for clarifying it. Will open another PR for 202012. Thanks.

PR #2063 created for 202012.

**Comment by stephenxs** [comment]
Currently, the PR depends on #2118 for the vstest failure.

**Pull request closed without merging**
