### PR TITLE
Add retryCount option for orchagent_restart_check program.

### PR DESCRIPTION
**Pull request by jipanyang**
Signed-off-by: Jipan Yang <jipan.yang@alibaba-inc.com>

**What I did**
Add --retryCount (-r) option for orchagent_restart_check,  so it may stay listening on the RESTARTCHECKREPLY notification channel for the whole retry period. 

**Why I did it**
This is a try to address issue: https://github.com/Azure/sonic-swss/issues/827
**How I verified it**

Issue orchagent_restart_check with -r option
```
admin@sonic:~$ docker exec -i swss /usr/bin/orchagent_restart_check -r 5
RESTARTCHECK succeeded
```

```
Apr 10 22:21:44.758066 sonic NOTICE swss#orchagent_restart_check: main:90: Number of retries for the request to orchagent is set to 5
Apr 10 22:21:44.758530 sonic INFO swss#orchagent_restart_check: subscribe:60: subscribed to RESTARTCHECKREPLY
Apr 10 22:21:44.758530 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 0
Apr 10 22:21:44.758530 sonic NOTICE swss#orchagent: doTask:163: RESTARTCHECK notification for orchagent 
Apr 10 22:21:44.758530 sonic NOTICE swss#orchagent: doTask:182: orchagent|NoFreeze:fasle|SkipPendingTaskCheck:fasle
Apr 10 22:21:44.758530 sonic NOTICE swss#orchagent: warmRestartCheck:556: Restart check result: READY
Apr 10 22:21:44.759160 sonic NOTICE swss#orchagent_restart_check: main:138: RESTARTCHECK success, orchagent is frozen and ready for warm restart
```

Issue the request again:
```
admin@sonic:~$ docker exec -i swss /usr/bin/orchagent_restart_check -r 5
```
Will fail due to orchagent has been frozen:

```
Apr 10 22:22:46.468704 sonic NOTICE swss#orchagent_restart_check: main:90: Number of retries for the request to orchagent is set to 5
Apr 10 22:22:46.469308 sonic INFO swss#orchagent_restart_check: subscribe:60: subscribed to RESTARTCHECKREPLY
Apr 10 22:22:46.469308 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 0
Apr 10 22:22:47.470780 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
Apr 10 22:22:47.470863 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 1
Apr 10 22:22:48.471525 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
Apr 10 22:22:48.471525 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 2
Apr 10 22:22:49.472819 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
Apr 10 22:22:49.472928 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 3
Apr 10 22:22:50.474083 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
Apr 10 22:22:50.474167 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 4
Apr 10 22:22:51.475369 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
Apr 10 22:22:51.475369 sonic NOTICE swss#orchagent_restart_check: main:127: requested orchagent to do warm restart state check, retry count: 5
Apr 10 22:22:52.476797 sonic NOTICE swss#orchagent_restart_check: main:150: RESTARTCHECK for  timed out
```
RESTARTCHECK failed
**Details if related**

### CODE REVIEW

**Comment by yxieca** [comment]
I am now more leaning towards the DB solution. This change only solves the problem as long as orchagent_restart_check didn't quit. But DB solution can support even if we retry warm-reboot.

And BTW, orchagent_restart_check  should be renamed to something like pause_orchagent

**Comment by jipanyang** [comment]
> I am now more leaning towards the DB solution. This change only solves the problem as long as orchagent_restart_check didn't quit. But DB solution can support even if we retry warm-reboot.
> 
> And BTW, orchagent_restart_check should be renamed to something like pause_orchagent

I'm not sure if I get it, for warm-reboot retry,  orchagent_restart_check will be started again.  If there is no reply in 10 ~12 seconds for 6 RESTARTCHECK signal,  the system should be in wrong state, no further warm restart should be tried. 

Below is a snippet of docker warm upgrade code we use, jut fyi.   
```
            cmd = "docker exec -i swss orchagent_restart_check -w 2000 -r 5 " + skipPendingTaskCheck

            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
            (out, err) = proc.communicate()
            if proc.returncode != 0:
                if not skip_check:
                    click.echo("Orchagent is not in clean state, RESTARTCHECK failed")
                    # Restore orignal config before exit
                    if warm_configured == False and warm:
                        run_command("config warm_restart disable %s" % container_name)
                    sys.exit(proc.returncode)
                else:
                    click.echo("Orchagent is not in clean state, upgrading it anyway")
            else:
                click.echo("Orchagent is in clean state and frozen for warm upgrade")
```

But please go ahead with the DB solution implementation. I don't see any major issue with that approach either.

**Comment by yxieca** [comment]
This might be an extreme example, but what if the orchagent takes 12 second to complete pausing? Most of the time were spent draining the queue? restart_check gave up after 10 seconds, and then you have a paused orchagent and unable to warm-reboot?

**Comment by jipanyang** [comment]
> This might be an extreme example, but what if the orchagent takes 12 second to complete pausing? Most of the time were spent draining the queue? restart_check gave up after 10 seconds, and then you have a paused orchagent and unable to warm-reboot?

With DB solution,  the same issue needs to be handled as well.  If orchagent has been in paused state for too long before another warm reboot retry, the state of whole system is messed up likely.  In that case you might want a clean cold upgrade.

**Comment by jipanyang** [comment]
Got some time to think about the problem a little bit more, actually just before orchagent pauses itself, a "paused" state could be set to warm_restart_table:  https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md#warm_restart_table

This way orchagent_restart_check problem may check the flag before trying to send out RESTARTCHECK siginal to orchagent, if it is already in paused state, just clear the state and return success(?). 

This also gives more visibility of orchagent state,

Currently we check pending task state of orchagent, there might be more states to check for processes in  swss container.

**Comment by yxieca** [comment]
@jipanyang  please make the matching sonic-utilities change.

**Comment by jipanyang** [comment]
@yxieca yes, please check sonic-utilities update: https://github.com/Azure/sonic-utilities/pull/555

**Comment by yxieca** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by yxieca** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
