### PR TITLE
[orchagent]: Fix ACL input attributes validation.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
- Move string to int converters to swss-common repo
- Use common converters in Everflow and ACL code

### CODE REVIEW

**Comment by oleksandrivantsiv** [comment]
Depends on https://github.com/Azure/sonic-swss-common/pull/83 PR

**Comment by pavel-shirshov** [comment]
Oleksandr, can you please update your PR to initiate another check. I've pushed your https://github.com/Azure/sonic-swss-common/pull/83

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
@pavel-shirshov: You can force the Jenkins pull request builder to initiate a new test be commenting "Retest this please" as I did above.

**Pull request merged**
