### PR TITLE
Ignore testcase in Debian Jessie

### PR DESCRIPTION
**Pull request by qiluo-msft**

### CODE REVIEW

**Comment by stcheng** [comment]
I'm okay with this. But I'm not sure how long do we want to keep the code/test compatible with the old kernel.

**Comment by prsunny** [comment]
Just thinking, should we skip or should we just fail the test? IMO, this is a valid use-case.

**Comment by lguohan** [comment]
@qiluo-msft  will remove it after upgrading to stretch?

**Comment by qiluo-msft** [comment]
I will remove it either:
1. we have fix on Debian Jessie
2. we don't have development tasks on Debian Jessie branches, ie. the old branches are almost frozen for dev.

**Pull request merged**
