### PR TITLE
Clean code, remove unused header file

### PR DESCRIPTION
**Pull request by qiluo-msft**
**What I did**
The RedisClient class is deprecated so no need to include the header file.

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by daall** [comment]
retest vs please

**Comment by qiluo-msft** [comment]
Retest vs please

**Review by daall — APPROVED** [review]

**Pull request merged**
