### PR TITLE
[VS} Skip consistent fail tests

### PR DESCRIPTION
**Pull request by prsunny**
**What I did**
Skip tests that are failing consistently.

**Why I did it**
Unblock PRs

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@theasianpianist for viz

**Review by theasianpianist — APPROVED** [review]

**Comment by prsunny** [comment]
@stephenxs , could you please take a look at the test_buffer_dynamic tests? Some of the tests in this file has frequent failures and we would like to understand the root-cause.

**Comment by stephenxs** [comment]
> @stephenxs , could you please take a look at the test_buffer_dynamic tests? Some of the tests in this file has frequent failures and we would like to understand the root-cause. @neethajohn

Sure. will do.

**Comment by vivekreddynv** [comment]
test_removebufferpool is failing for 202111 PR's. This PR has to be backported to 202111

**Pull request merged**
