### PR TITLE
Add synchronous switch to orch agent

### PR DESCRIPTION
**Pull request by kcudnik**
**What I did**
Implement synchronous flag for orchestration agent

**Why I did it**
To allow dynamic enable synchronous mode from command line

**How I verified it**
Running from command line and checking if attribute was passed to sairedis lib and waiting for response from syncd.

**Details if related**
Related to https://github.com/Azure/sonic-sairedis/pull/476

### CODE REVIEW

**Comment by kcudnik** [comment]
can't figure out why build on VS is failing, but pretty sure it;s not this change

**Comment by jleveque** [comment]
Retest vs please

**Comment by jleveque** [comment]
Retest vs please.

**Comment by jleveque** [comment]
Retest this please

**Comment by stcheng** [comment]
Retest this please

**Comment by stcheng** [comment]
Retest this please

**Comment by lguohan** [comment]
Retest this please

**Pull request merged**
