### PR TITLE
[virtual test] fix a unstable egress ACL test

### PR DESCRIPTION
**Pull request by keboliu**
**What I did**
fix egress ACL table creation test.  

**Why I did it**
the test could failed sometimes. 
**How I verified it**
run virtual test
**Details if related**

### CODE REVIEW

**Comment by keboliu** [comment]
retest please

**Comment by keboliu** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by lguohan** [comment]
this is good fix. the two failures are not caused by this PR.

TestSpeedSet.test_SpeedAndBufferSet
test_PortAutoNeg_warm

**Comment by jipanyang** [comment]
> this is good fix. the two failures are not caused by this PR.
> 
> TestSpeedSet.test_SpeedAndBufferSet
> test_PortAutoNeg_warm
I was scratching my head about these two failing case on my local environment. Same swss code, passed before but failing now. Guess some sonic-buildimage vs change triggered the failure.

**Comment by lguohan** [comment]
i'll send pr to fix them shortly.

**Pull request merged**
