### PR TITLE
Add dot1p to tc mapping support

### PR DESCRIPTION
**Pull request by wendani**
**What I did**

**Why I did it**

**How I verified it**
Manual test on brcm with the following configuration add-on:

    "DOT1P_TO_TC_MAP": {
        "AZURE": {
            "1": "6",
            "0": "0",
            "3": "3",
            "2": "5",
            "5": "2",
            "4": "4",
            "7": "0",
            "6": "1"
        }
    },
    "PORT_QOS_MAP": {
        "Ethernet4,Ethernet8,Ethernet12,Ethernet16,Ethernet20,Ethernet24,Ethernet28,Ethernet32,Ethernet36,Ethernet40,Ethernet44,Ethernet48,Ethernet52,Ethernet56,Ethernet60,Ethernet64,Ethernet68,Ethernet72,Ethernet76,Ethernet80,Ethernet84,Ethernet88,Ethernet92,Ethernet96,Ethernet112,Ethernet116,Ethernet120,Ethernet124": {
            "tc_to_pg_map": "[TC_TO_PRIORITY_GROUP_MAP|AZURE]",
            "tc_to_queue_map": "[TC_TO_QUEUE_MAP|AZURE]",
            "dot1p_to_tc_map": "[DOT1P_TO_TC_MAP|AZURE]",
            "pfc_enable": "3,4",
            "pfc_to_queue_map": "[MAP_PFC_PRIORITY_TO_QUEUE|AZURE]"
        }
    },

1) mem diag dump is correct
2) dot1p to pg mapping is correct
3) dot1p to queue mapping is correct
4) dot1p 3 triggers PFC3
5) dot1p 4 triggers PFC4

vs test commands:
```
sonic-buildimage/src/sonic-swss/tests$ sudo pytest test_qos_map.py::TestDot1p::test_dot1p_cfg --dvsname=vs
```
```
sonic-buildimage/src/sonic-swss/tests$ sudo pytest test_qos_map.py::TestDot1p::test_port_dot1p --dvsname=vs
```
**Details if related**
Depend on:
schema update: https://github.com/Azure/sonic-swss-common/pull/274

### CODE REVIEW

**Comment by lguohan** [comment]
missing vs test.

**Comment by wendani** [comment]
Added dot1p profile test and dot1p profile applying to ports test
https://github.com/Azure/sonic-swss/pull/871#pullrequestreview-245410035

**Comment by wendani** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Pull request merged**
