### PR TITLE
[VS test][202106] Increase vs test timeout to 240 seconds

### PR DESCRIPTION
**Pull request by dgsudharsan**
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>

**What I did**
Increase vs test timeout to 240 seconds similar to https://github.com/Azure/sonic-swss/pull/1988

**Why I did it**
Started observing the following error:

##[error]The job running on agent Azure Pipelines 5 ran longer than the maximum time of 180 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@dgsudharsan could you please review failures?

**Comment by dgsudharsan** [comment]
> @dgsudharsan could you please review failures?

Looks like infrastructure issue. @lguohan  @prsunny  Can you please help?

**Review by prsunny — APPROVED** [review]

**Pull request closed without merging**
