### PR TITLE
remove 00-copp.config.json from swss debian package

### PR DESCRIPTION
**Pull request by abdosi**
Removed 00-copp.config.json from swss debian package

Changes to make copp.json as j2 template based based on device role.
copp.json.j2 is moved into docker-orchagent. docker-init.sh of orchagent will create json file form j2 template.

This PR is dependent on : https://github.com/Azure/sonic-buildimage/pull/5053

### CODE REVIEW

**Comment by lguohan** [comment]
why is there conflict?

**Comment by abdosi** [comment]
> why is there conflict?

rebased with master.

**Comment by lguohan** [comment]
why do we have so many vstest failures?

**Comment by abdosi** [comment]
retest vs please

**Comment by abdosi** [comment]
retest this please

**Comment by lguohan** [comment]
since you have remove copp json, are these genuine failures?

**Comment by abdosi** [comment]
> since you have remove copp json, are these genuine failures?

don't think so. failures are random and many other PR's have failure is past few days. Meanwhile I am trying to run locally also to re-confirm.

**Comment by abdosi** [comment]
retest this please

**Comment by abdosi** [comment]
retest this please

**Comment by abdosi** [comment]
retest this please

**Comment by abdosi** [comment]
vs failures are not related copp.json removal. copp.json is not loaded in DVS testing environment. APP_DB does not have copp entry.  Basically this failures are random and not impacted by this change. 

To confirm run manually 4 failed test case of last vs test iteration and all are passing:

sudo pytest --dvsname=vs -v test_port_dpb_acl.py::TestPortDPBAcl::test_acl_table_empty_port_list
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.9, pytest-4.6.9, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/azure/sonic-swss/tests
plugins: flaky-3.7.0
collected 1 item

test_port_dpb_acl.py::TestPortDPBAcl::test_acl_table_empty_port_list ^[[APASSED                       [100%]

====================================== 1 passed in 105.06 seconds =======================================
azure@str-acs-serv-18:~/sonic-swss/tests$ sudo pytest --dvsname=vs -v test_port_dpb_acl.py::TestPortDPBAcl::test_one_port_two_acl_tables
========================================== test session starts ==========================================
platform linux -- Python 3.6.9, pytest-4.6.9, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/azure/sonic-swss/tests
plugins: flaky-3.7.0
collected 1 item

test_port_dpb_acl.py::TestPortDPBAcl::test_one_port_two_acl_tables PASSED                         [100%]

====================================== 1 passed in 105.91 seconds =======================================
azure@str-acs-serv-18:~/sonic-swss/tests$ sudo pytest --dvsname=vs -v test_port_dpb_acl.py::TestPortDPBAcl::test_one_acl_table_many_ports
========================================== test session starts ==========================================
platform linux -- Python 3.6.9, pytest-4.6.9, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/azure/sonic-swss/tests
plugins: flaky-3.7.0
collected 1 item

test_port_dpb_acl.py::TestPortDPBAcl::test_one_acl_table_many_ports PASSED                        [100%]

====================================== 1 passed in 131.79 seconds =======================================
azure@str-acs-serv-18:~/sonic-swss/tests$ test_one_port_many_acl_tables^C
azure@str-acs-serv-18:~/sonic-swss/tests$ sudo pytest --dvsname=vs -v test_port_dpb_acl.py::TestPortDPBAcl::test_one_port_many_acl_tables
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.9, pytest-4.6.9, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/azure/sonic-swss/tests
plugins: flaky-3.7.0
collected 1 item

test_port_dpb_acl.py::TestPortDPBAcl::test_one_port_many_acl_tables PASSED                                                                                                                                  [100%]

=========================================================================================== 1 passed in 128.02 seconds ============================================================================================

**Comment by abdosi** [comment]
@lguohan Can we merge this ?

**Comment by abdosi** [comment]
retest this please

**Pull request merged**
