### PR TITLE
Revert changelog that was done for passing VS test.

### PR DESCRIPTION
**Pull request by prsunny**
**What I did**
Revert changelog that was done for passing VS test as part of https://github.com/Azure/sonic-swss/pull/977

**Why I did it**
Original issue is fixed as part of  Azure/sonic-build-tools@e9e3957

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@shine4chen , @tylerlinp FYI

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
Yes @zhenggen-xu , I couldn't merge this PR due to VS test failure. I think reverting this change is a better plan.

**Comment by prsunny** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Pull request merged**
