### PR TITLE
[port_rates][rif_rates] Fix port_rates.lua

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

**What I did**
Set rate collect logic init state per port
**Why I did it**
Observing following syslog:
`Nov 26 19:34:28.821608 sonic ERR syncd[26]: :- guard: RedisReply catches system_error: command: *39#015#012$7#015#012EVALSHA#015#012$40#015#0121140a72bbf8e5306e589cb798796067294922901#015#012$2#015#01232#015#012$19#015#012oid:0x600000000034f#015#012$19#015#012oid:0x6000000000350#015#012$19#015#012oid:0x6000000000351#015#012$19#015#012oid:0x6000000000352#015#012$19#015#012oid:0x6000000000353#015#012$19#015#012oid:0x6000000000354#015#012$19#015#012oid:0x6000000000355#015#012$19#015#012oid:0x6000000000356#015#012$19#015#012oid:0x6000000000357#015#012$19#015#012oid:0x6000000000358#015#012$19#015#012oid:0x6000000000359#015#012$19#015#012oid:0x600000000035a#015#012$19#015#012oid:0x600000000035b#015#012$19#015#012oid:0x600000000035c#015#012$19#015#012oid:0x600000000035d#015#012$19#015#012oid:0x600000000035e#015#012$19#015#012oid:0x600000000035f#015#012$19#015#012oid:0x6000000000360#015#012$19#015#012oid:0x6000000000361#015#012$19#015#012oid:0x6000000000362#015#012$19#015#012oid:0x6000000000363#015#012$19#015#012oid:0x6000000000364#015#012$19#015#012oid:0x6000000000365#015#012$19#015#012oid:0x6000000000366#015#012$19#015#012oid:0x6000000000367#015#012$19#015#012oid:0x6000000000368#015#012$19#015#012oid:0x6000000000369#015#012$19#015#012oid:0x600000000036a#015#012$19#015#012oid:0x600000000036b#015#012$19#015#012oid:0x600000000036c#015#012$19#015#012oid:0x600000000036d#015#012$19#015#012oid:0x600000000036e#015#012$1#015#0122#015#012$8#015#012COUNTERS#015#012$7#015#0121000000#015#012$2#015#012''#015#012, reason: ERR Error running script (call to f_1140a72bbf8e5306e589cb798796067294922901): @user_script:47: user_script:47: attempt to perform arithmetic on local 'in_octets_last' (a boolean value) : Input/output error
Nov 26 19:34:28.821608 sonic ERR syncd[26]: :- runRedisScript: Caught exception while running Redis lua script: ERR Error running script (call to f_1140a72bbf8e5306e589cb798796067294922901): @user_script:47: user_script:47: attempt to perform arithmetic on local 'in_octets_last' (a boolean value) : Input/output error
`
loop sets DONE state on processing the first port, leaving the rest of the ports' states uninitialized.

**How I verified it**
Checked redis-cli -n 2 hgetall RATES:oid:<oid> to ensure `_last` fields are set.
**Details if related**

### CODE REVIEW

**Comment by vboykox** [comment]
@mykolaf @wangxin @lguohan

**Comment by vboykox** [comment]
retest vs please

**Comment by vboykox** [comment]
@mykolaf @wangxin @lguohan

**Comment by daall** [comment]
@lguohan this fix is needed for https://github.com/Azure/sonic-mgmt/pull/2434

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
@vboykox, do we need to backport this to previous 201911 branch?

**Comment by vboykox** [comment]
@lguohan, no

**Pull request merged**
