### PR TITLE
Revert recirc port change

### PR DESCRIPTION
**Pull request by ysmanman**
**What I did**
Revert the special handling for recirc port.

**Why I did it**
Recirc port support has been added to recent versions of DNX SAI. The earlier special handling for recirc port is not required anymore and thus reverted.

**How I verified it**
I tested the PR with SAI 5.0.0.5 and verified inband port came up and functioned correctly.

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
please give the PR number that you reverted

**Comment by ysmanman** [comment]
> please give the PR number that you reverted

@prsunny This is the PR that added special handling for recirc ports: https://github.com/Azure/sonic-swss/pull/1530.

**Review by abdosi — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This is not an exact revert. It is not revert 1530 completely.

Since it is merged. Can we revert both commits
```
7c7c4513 2021-07-06 | Revert recirc port change (#1813) [Song Yuan]
5ef4b382 2021-06-01 | Add support for recirc port and everflow (#1530) [Song Yuan]
```

@prsunny  @abdosi for vis.

**Comment by qiluo-msft** [comment]
I create another PR https://github.com/Azure/sonic-swss/pull/1911 to revert both.

**Comment by qiluo-msft** [comment]
@ysmanman Could you help check why swss-common master branch keep failing on test case "test_recirc_port"?
https://dev.azure.com/mssonic/build/_build/results?buildId=36930&view=ms.vss-test-web.build-test-results-tab

**Pull request merged**
