### PR TITLE
Fix next hop compilation

### PR DESCRIPTION
**Pull request by TACappleman**
**What I did**
Fixed compilation of SWSS following last 2 commits

**Why I did it**
Last 2 commits don't compile together due to change in nexthop(group)key definitions

**How I verified it**
Compiled with this fix

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
why is lgtm failing? @kperumalbfn , please review

**Comment by TACappleman** [comment]
LGTM fails because it tries to compile the previous commit for comparison

**Review by prsunny — APPROVED** [review]

**Comment by kperumalbfn** [comment]
@TACappleman Not sure why it is failing after merge.

**Review by kperumalbfn — APPROVED** [review]

**Comment by TACappleman** [comment]
@kperumalbfn the previous commit (which merged around the same time) referenced one of the functions you'd added a variable to. There was no merge conflict between them, but the combo then couldn't compile

**Comment by kperumalbfn** [comment]
> @kperumalbfn the previous commit (which merged around the same time) referenced one of the functions you'd added a variable to. There was no merge conflict between them, but the combo then couldn't compile

Thanks @TACappleman

**Pull request merged**
