### PR TITLE
Fix: missing sonic-db-cli in docker-sonic-vs image

### PR DESCRIPTION
**Pull request by qiluo-msft**
**What I did**
Fix: missing sonic-db-cli in docker-sonic-vs image

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by liuh-80** [comment]
This PR blocked by some randomly failed UTs:

2022-06-29T05:12:36.1057643Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_creation FAILED [ 82%]
2022-06-29T05:12:36.2205230Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_add_ip_addrs FAILED [ 82%]
2022-06-29T05:12:36.2932181Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_appl_db_proc_seq FAILED [ 82%]
2022-06-29T05:12:36.3673395Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_admin_status_change FAILED [ 82%]
2022-06-29T05:12:36.4672083Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_remove_ip_addrs FAILED [ 83%]
2022-06-29T05:12:36.5390488Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_removal FAILED [ 83%]
2022-06-29T05:12:36.6127161Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_mtu FAILED    [ 83%]
2022-06-29T05:12:36.7097591Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_nhg_accel FAILED [ 83%]
2022-06-29T05:12:36.7853144Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_oper_down_with_pending_neigh_route_tasks FAILED [ 83%]


2022-06-28T21:50:18.0131695Z _________________ TestSubPortIntf.test_sub_port_intf_creation __________________
2022-06-28T21:50:18.0131990Z 
2022-06-28T21:50:18.0132733Z self = <test_sub_port_intf.TestSubPortIntf object at 0x7f29ce750550>
2022-06-28T21:50:18.0133202Z dvs = <conftest.DockerVirtualSwitch object at 0x7f29ceacdbb0>
2022-06-28T21:50:18.0133402Z 
2022-06-28T21:50:18.0133771Z     def test_sub_port_intf_creation(self, dvs):
2022-06-28T21:50:18.0135106Z >       self.connect_dbs(dvs)
2022-06-28T21:50:18.0136417Z 
2022-06-28T21:50:18.0136685Z test_sub_port_intf.py:585: 
2022-06-28T21:50:18.0137137Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-06-28T21:50:18.0137489Z test_sub_port_intf.py:86: in connect_dbs
2022-06-28T21:50:18.0137840Z     self.default_vrf_oid = self.get_default_vrf_oid()
2022-06-28T21:50:18.0138213Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-06-28T21:50:18.0138395Z 
2022-06-28T21:50:18.0138720Z self = <test_sub_port_intf.TestSubPortIntf object at 0x7f29ce750550>
2022-06-28T21:50:18.0138949Z 
2022-06-28T21:50:18.0139206Z     def get_default_vrf_oid(self):
2022-06-28T21:50:18.0139657Z         oids = self.get_oids(ASIC_VIRTUAL_ROUTER_TABLE)
2022-06-28T21:50:18.0140093Z >       assert len(oids) == 1, "Wrong # of default vrfs: %d, expected #: 1." % (len(oids))
2022-06-28T21:50:18.0140508Z E       AssertionError: Wrong # of default vrfs: 2, expected #: 1.
2022-06-28T21:50:18.0140833Z E       assert 2 == 1
2022-06-28T21:50:18.0141416Z E         -2
2022-06-28T21:50:18.0141662Z E         +1

**Comment by liuh-80** [comment]
The cli issue been fixed by this PR: https://github.com/Azure/sonic-buildimage/pull/11282
However, this PR still need complete and merge, after that, we can add the reverted PR back.

**Pull request merged**
