### PR TITLE
[mclaglink] fix acl out ports

### PR DESCRIPTION
**Pull request by novikauanton**
**What I did**

Delete redundant copy to remove string duplication.

**Why I did it**

`isolate_dst_port` is initialized as blank string,
```
    string isolate_dst_port;
```

 then data is inserted into the begining

 ```
    isolate_dst_port.insert(0, (const char*)cur, op_hdr->op_len);
    // now isolate_dst_port = "PortChannel0001,Ethernet0"
 ```

 then isolate_dst_port is printed to logs:
```
        SWSS_LOG_NOTICE("set port isolate, src port: %s, dst port: %s",
                isolate_src_port.c_str(), isolate_dst_port.c_str());
```
Logs:
```
Nov 12 15:45:40.848696 sonic NOTICE iccpd#mclagsyncd: :- setPortIsolate: set port isolate, src port: PortChannel0002, dst port: PortChannel0001,Ethernet0
```

neither `op_hdr`, neither `isolate_dst_port` changed, but same string from `op_hdr` is inserted into the `isolate_dst_port`.
```
    isolate_dst_port.insert(0, (const char*)cur, op_hdr->op_len);
    // now isolate_dst_port = "PortChannel0001,Ethernet0PortChannel0001,Ethernet0"
```

after splitting the string by `,` first entry is skipped, as it starts with `PortChannel`, and final attr is `Ethernet0PortChannel0001,Ethernet0`

Logs:
```
Nov 12 15:45:41.659344 sonic ERR swss#orchagent: :- doAclRuleTask: Unknown or invalid rule attribute 'OUT_PORTS : Ethernet0PortChannel0001,Ethernet0'
```

**How I verified it**

Configure MC-LAG as described in issue https://github.com/Azure/sonic-swss/issues/1938 .

### CODE REVIEW

**Comment by novikauanton** [comment]
@prsunny  could you please review it?

**Comment by gechiang** [comment]
@Praveen-Brcm 
Can you help take a look at this change please.
Thanks!

**Comment by novikauanton** [comment]
@gechiang @Praveen-Brcm looks like the whole function does not work at all because it consists of 2 cases: [port isolation group](https://github.com/novikauanton/sonic-swss/blob/4664ead03c220bb91ef97746f3dd97232be46828/mclagsyncd/mclaglink.cpp#L192) and [ACL isolation](https://github.com/novikauanton/sonic-swss/blob/4664ead03c220bb91ef97746f3dd97232be46828/mclagsyncd/mclaglink.cpp#L273).
ACL isolation does not work due to this issue. 
Port isolation does not work because it use [env `platform` to check its condition](https://github.com/novikauanton/sonic-swss/blob/4664ead03c220bb91ef97746f3dd97232be46828/mclagsyncd/mclaglink.cpp#L191) and `mclagsyncd` work inside `iccpd` container and [`iccpd` container does not set `platform` env](https://github.com/Azure/sonic-buildimage/pull/8945) so code in port isolation branch will never be executed.

**Review by Praveen-Brcm — APPROVED** [review]
Changes looks good. Thanks.

**Comment by prsunny** [comment]
@gechiang , could you please sign-off and merge this PR?

**Review by gechiang — APPROVED** [review]

**Pull request merged**
