### PR TITLE
[201911] Fixes for NAT lgtm alerts

### PR DESCRIPTION
**Pull request by AkhileshSamineni**
This PR is similar as https://github.com/Azure/sonic-swss/pull/1320 which is merged on master branch.

Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
@abdosi Could you please merge this PR.

**Comment by AkhileshSamineni** [comment]
@abdosi  LGTM always fails on 201911 branch as we known with below errors

[2020-08-10 05:59:53] [build] fpmsyncd.cpp:3:10: fatal error: logger.h: No such file or directory
[2020-08-10 05:59:53] [build]     3 | #include "logger.h"
[2020-08-10 05:59:53] [build]       |          ^~~~~~~~~~
[2020-08-10 05:59:53] [build] compilation terminated.

**Review by arlakshm — APPROVED** [review]
LGTM

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by rlhui** [comment]
This PR is similar as #1320 which is merged on master branch.

Signed-off-by: Akhilesh Samineni akhilesh.samineni@broadcom.com

**Pull request merged**
