### PR TITLE
Fix bug that show-mac CLI can't display mac address from lag

### PR DESCRIPTION
**Pull request by shine4chen**
**What I did**
fix bug that show-mac CLI can't display mac address from lag

**Why I did it**

**How I verified it**
Complie and test it on nephos lab

**Details if related**

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by prsunny** [comment]
@shine4chen , can you check this [PR ](https://github.com/Azure/sonic-swss/pull/885/files) and address the comment?.

**Comment by prsunny** [comment]
> @shine4chen , can you check this PR  and address the comment?.
Just noticed, @anilkpandey replied that he would address the comment and resubmit. This PR can be closed based on that changes.

**Comment by leoli-nps** [comment]
Same as [PR#808](https://github.com/Azure/sonic-swss/pull/808) and [PR#885](https://github.com/Azure/sonic-swss/pull/885)
When they fix it according to the comments, this PR can be closed.

**Comment by shine4chen** [comment]
@prsunny  Sure, I close this PR.

**Pull request closed without merging**
