### PR TITLE
[vlan] Add pytest cases to verify data in app db and state db.

### PR DESCRIPTION
**Pull request by linemma**
Signed-off-by: Emma Lin <emma_lin@edge-core.com>

**What I did**
[vlan] Add pytest cases to verify data in app db and state db.

**Why I did it**

**How I verified it**
Add test case:
1. Check app db and state db after create vlan. => succeed
2. Check app db and state db after add vlan member. => succeed

**Details if related**
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: /home/ubuntu/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 15 items

test_vlan.py::TestVlan::test_VlanAddRemove PASSED [  6%]
test_vlan.py::TestVlan::test_MultipleVlan PASSED  [ 13%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input0-0] PASSED [ 20%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input1-0] PASSED [ 26%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input2-0] PASSED [ 33%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectKeyPrefix[test_input3-1] PASSED [ 40%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input0-0] PASSED [ 46%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input1-0] PASSED [ 53%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input2-0] PASSED [ 60%]
test_vlan.py::TestVlan::test_AddVlanWithIncorrectValueType[test_input3-1] PASSED [ 66%]
test_vlan.py::TestVlan::test_AddMaxVlan PASSED [ 73%]
test_vlan.py::TestVlan::test_VlanDbData PASSED [ 80%]
test_vlan.py::TestVlan::test_VlanMemberDbData[test_input0-expected0] PASSED [ 86%]
test_vlan.py::TestVlan::test_VlanMemberDbData[test_input1-expected1] PASSED [ 93%]
test_vlan.py::TestVlan::test_VlanMemberDbData[test_input2-expected2] PASSED [100%]

### CODE REVIEW

**Comment by linemma** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@linemma, I am not able to resolve the conflict. Can you resolve the conflict so that we can merge?

**Comment by linemma** [comment]
@lguohan, resolved, please review. Thanks.

**Comment by lguohan** [comment]
thank you!

**Pull request merged**
