### PR TITLE
build debug symbol package

### PR DESCRIPTION
**Pull request by lguohan**

### CODE REVIEW

**Comment by garyachy** [comment]
Please describe how to use this debug package.
Is it loaded to container automatically?

**Comment by lguohan** [comment]
No, it does not loaded to container automatically, you need to manually install the package into the container. Just install the swss-dbg package and then you can get the symbols in gdb.

https://wiki.debian.org/HowToGetABacktrace

**Comment by garyachy** [comment]
@stcheng. @lguohan I can not find swss-dbg package after I build SONIC dockers.

I see only the following debug packages:
./src/libnl3/libnl-3-200-dbg_3.2.27-1_amd64.deb
./src/quagga-dbg_0.99.24.1-2.1_amd64.deb
./target/debs/libsnmp30-dbg_5.7.3+dfsg-1.5_amd64.deb
./target/debs/libhiredis-dbg_0.13.3-2_amd64.deb

Please advise how to generate swss-dbg

**Comment by garyachy** [comment]
My fault, I have not updated to the latest. Now I see swss-dbg_1.0.0_amd64.deb

**Pull request merged**
