### PR TITLE
intfsyncd: Returning when scope == RT_SCOPE_UNIVERSE

### PR DESCRIPTION
**Pull request by stcheng**
intfsyncd: Returning when scope == RT_SCOPE_UNIVERSE

### CODE REVIEW

**Comment by kcudnik** [comment]
Ack

**Comment by eladraz** [comment]
Why not having this logic in the OA?
And if for some reason you don't want to add local route, please remove the "scope", and fix documentation as well.

**Comment by lguohan** [comment]
agree with elad. seems to be more flexible to have the filtering logic in OA.

**Comment by stcheng** [comment]
if we have this logic in OA, then we will need the filtering for both set and del. the set logic is easy because we have attributes indicating the family and scope. but for the del part, it is hard because it doesn't contain any more information. when we put logic into OA, it means that in application database we also have such local entries that we do not want to sync to the asic. it would be more reasonable if we don't have such entries in the application database.

**Pull request merged**
