### PR TITLE
[202012] [CoPP] Enable CoPP UT

### PR DESCRIPTION
**Pull request by noaOrMlnx**
**What I did**
Enable CoPP UT in docker-sonic-vs.

**Why I did it**
N/A

**How I verified it**
Run Copp UT and make sure all tests pass

**Details if related**
Tests will pass after https://github.com/Azure/sonic-buildimage/pull/10230 will be merged

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@noaOrMlnx please handle LGTM new alrest and rerun checkers.

**Comment by prsunny** [comment]
@noaOrMlnx , can you please take a look at the `trap `VS test failures.

**Comment by xumia** [comment]
@noaOrMlnx , fixed a build issue in 202012 branch in sonic-buildimage, please use "/azpw run" to do another try if the issue is relative to not use latest vs image in download sonic-buildimage step. https://dev.azure.com/mssonic/build/_build/results?buildId=85104&view=logs&j=ec04b24c-02f9-5d3d-ea93-ae01af596cc2&t=198deee3-3b76-5994-5f0a-502563e8627e

**Pull request merged**
