### PR TITLE
[202111] Support mock_test infra for dynamic buffer manager and fix issues found during mock test (#2234)

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**
This PR is to backport https://github.com/Azure/sonic-swss/pull/2234

**Why I did it**
Support mock_test infra for dynamic buffer manager and fix issues found during mock test

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@stephenxs  can you please check if this can be moved to ready for review and re run checkers?

**Comment by stephenxs** [comment]
Same issue as we saw on master - time out

**Comment by liat-grozovik** [comment]
@stephenxs  could you please check failures?

**Comment by stephenxs** [comment]
All failures are the same
```
e = HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create')

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create: Not Found ("No such image: docker-sonic-vs:Azure.sonic-swss.20220622.13")
```

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
