### PR TITLE
update to SAI 1.2

### PR DESCRIPTION
**Pull request by lguohan**
**What I did**
Update SAI to 1.2

**Why I did it**
Bring new SAI features for SONiC

**How I verified it**
using virtual switch.

**Details if related**
Depends on https://github.com/Azure/sonic-sairedis/pull/264

### CODE REVIEW

**Comment by lguohan** [comment]
Do not merge, need to actual SAI to be available.

**Comment by lguohan** [comment]
on the lag part, it is due to change of sai spec, pvid should be a lag attribute, not a lag member attribute.

**Comment by pavel-shirshov** [comment]
Got it. Thanks.

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
