### PR TITLE
[pbh] [aclorch] Fixed a bug causes by updating the flow-counter value for the PBH rule

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**What I did**
Added the register and deregister functions for the flex counter before updating counters for the ACL rule.

**Why I did it**
Overcome SAI error in case of flow counters disabled and then enabled.

For example:

1. Show PBH rules:
```
root@sonic:/home/admin# show pbh rule
TABLE      RULE             PRIORITY    MATCH                                 HASH        ACTION         COUNTER
---------  ---------------  ----------  ------------------------------------  ----------  -------------  ---------
pbh_table  nvgre_ipv4_ipv4  2           gre_key:           0x2500/0xffffff00  inner_hash  SET_ECMP_HASH  ENABLED
                                        ether_type:        0x0800
                                        ip_protocol:       0x2f
                                        inner_ether_type:  0x0800
```

2. Update PBH rule:
```
root@sonic:/home/admin# config pbh rule update field set pbh_table nvgre_ipv4_ipv4  --flow-counter DISABLED
root@sonic:/home/admin# config pbh rule update field set pbh_table nvgre_ipv4_ipv4  --flow-counter ENABLED
```

3. Observed behavior:
```
NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set ACTION_COUNTER, key:ACL Entry [1], val:NULL,(0:0),0,0000,0
NOTICE syncd#SDK: [SAI_ACL.NOTICE] mlnx_sai_acl.c[14326]- mlnx_delete_acl_counter: Delete ACL Counter ACL Counter [311296] type (byte:true, packet:true)
NOTICE swss#orchagent: :- updateRule: Successfully updated ACL rule nvgre_ipv4_ipv4 in table pbh_table
NOTICE swss#orchagent: :- updatePbhRule: Updated PBH rule(pbh_table|nvgre_ipv4_ipv4) in SAI
ERR syncd#SDK: [GBIN_ALLOCATOR.ERR] LID 38 doesn't exist!
ERR syncd#SDK: [FLOW_COUNTER.ERR] spectrum_flow_counter_lock: cm_lock failed [lid=38, flow_counter_id=311296]
ERR syncd#SDK: [FLOW_COUNTER.ERR] spectrum_flow_counter_get: spectrum_flow_counter_lock failed [cntr_id=311296]
ERR syncd#SDK: [SAI_ACL.ERR] mlnx_sai_acl.c[13776]- mlnx_acl_counter_get:  Failure to get counter in SDK - Entry Not Found
ERR syncd#SDK: [SAI_UTILS.ERR] mlnx_sai_utils.c[1931]- get_dispatch_attribs_handler: Failed getting attrib SAI_ACL_COUNTER_ATTR_BYTES
ERR syncd#SDK: [SAI_UTILS.ERR] mlnx_sai_utils.c[2068]- sai_get_attributes: Failed attribs dispatch
WARNING syncd#SDK: :- collectAclCounterAttrs: Failed to get attr of ACL counter oid:0x9000000001680: SAI_STATUS_ITEM_NOT_FOUND
ERR syncd#SDK: [GBIN_ALLOCATOR.ERR] LID 38 doesn't exist!
```

**How I verified it**
Added a UT.

**Details if related**

### CODE REVIEW

**Review by nazariig — APPROVED** [review]

**Review by stepanblyschak — DISMISSED** [review]

**Comment by prsunny** [comment]
@anish-n , please review

**Review by stepanblyschak — APPROVED** [review]

**Review by nazariig — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@anish-n kindly reminder to review this PR

**Review by anish-n — APPROVED** [review]

**Pull request merged**
