### PR TITLE
[test]: Add Class object in each test script file

### PR DESCRIPTION
**Pull request by stcheng**
This is to get a better JUnitXML file and align all
the tests under the same level of hierarchy.

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

### CODE REVIEW

**Comment by stcheng** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build/test_results_analyzer/

to have a better view in the test results analyzer, all the tests need to be put into separated class objects.

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by lguohan** [comment]
I ran multiple tests, I suspect there is some genuine issue in the refactoring.

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by stcheng** [comment]
test_warm_reboot.py::TestWarmReboot::test_system_warmreboot_neighbor_syncup FAILED

this test failed constantly others are fine
i'll check this test

**Comment by stcheng** [comment]
All checks have passed
2 successful checks
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build-pr/406/
i'll try some more

**Comment by stcheng** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Pull request merged**
