### PR TITLE
[Buffer Orch] Support removing buffer port profile list

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

Support removing an entry from BUFFER_PORT_INGRESS/EGRESS_PROFILE_LIST table.
- To remove it, set the list as empty.

Add mock test to verify the change

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**

**How I verified it**

Mock test and manual test

**Details if related**

### CODE REVIEW

**Comment by stephenxs** [comment]
2/3 basic blocks identified as uncovered are actually covered.
1001~1005:
```
Thread 1 "tests" hit Breakpoint 1, BufferOrch::processIngressBufferProfileList (this=0x555555d56880, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1003
1003                    SWSS_LOG_INFO("Missing or invalid ingress buffer profile reference specified for:%s", key.c_str());
(gdb) bt
#0  BufferOrch::processIngressBufferProfileList (this=0x555555d56880, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1003
#1  0x00005555557e036c in BufferOrch::doTask (this=0x555555d56880, consumer=...) at /usr/include/c++/8/bits/basic_string.h:936
#2  0x00005555557e0736 in BufferOrch::doTask (this=<optimized out>) at ../../orchagent/bufferorch.cpp:1150
#3  0x00005555556a6e2e in bufferorch_test::BufferOrchTest_BufferOrchTestReferencingObjRemoveThenAdd_Test::TestBody (this=<optimized out>) at bufferorch_ut.cpp:481
```

1015~1021
```
Thread 1 "tests" hit Breakpoint 3, BufferOrch::processIngressBufferProfileList (this=0x555555d56880, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1019
1019            attr.value.objlist.count = 0;
(gdb) bt
#0  BufferOrch::processIngressBufferProfileList (this=0x555555d56880, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1019
#1  0x00005555557e036c in BufferOrch::doTask (this=0x555555d56880, consumer=...) at /usr/include/c++/8/bits/basic_string.h:936
#2  0x00005555557e0736 in BufferOrch::doTask (this=<optimized out>) at ../../orchagent/bufferorch.cpp:1150
#3  0x00005555556a6c90 in bufferorch_test::BufferOrchTest_BufferOrchTestReferencingObjRemoveThenAdd_Test::TestBody (this=<optimized out>) at bufferorch_ut.cpp:463
```

1072~1075:
```
1074                    SWSS_LOG_INFO("Missing or invalid egress buffer profile reference specified for:%s", key.c_str());
(gdb) bt
#0  BufferOrch::processEgressBufferProfileList (this=0x555555c88820, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1074
#1  0x00005555557e036c in BufferOrch::doTask (this=0x555555c88820, consumer=...) at /usr/include/c++/8/bits/basic_string.h:936
#2  0x00005555557e0736 in BufferOrch::doTask (this=<optimized out>) at ../../orchagent/bufferorch.cpp:1150
#3  0x00005555556a796b in bufferorch_test::BufferOrchTest_BufferOrchTestCreateAndRemoveEgressProfileList_Test::TestBody (this=0x555555f025c0) at bufferorch_ut.cpp:505
```

1086~1091
```
1088            SWSS_LOG_NOTICE("%s has been removed from BUFFER_PORT_EGRESS_PROFILE_LIST_TABLE", key.c_str());
(gdb) bt
#0  BufferOrch::processEgressBufferProfileList (this=0x555555c88820, tuple=std::tuple containing = {...}) at ../../orchagent/bufferorch.cpp:1088
#1  0x00005555557e036c in BufferOrch::doTask (this=0x555555c88820, consumer=...) at /usr/include/c++/8/bits/basic_string.h:936
#2  0x00005555557e0736 in BufferOrch::doTask (this=<optimized out>) at ../../orchagent/bufferorch.cpp:1150
#3  0x00005555556a7fb0 in bufferorch_test::BufferOrchTest_BufferOrchTestCreateAndRemoveEgressProfileList_Test::TestBody (this=0x555555f025c0) at bufferorch_ut.cpp:542
```

Basic blocks `1006~1007` and `1077~1078` are not covered because in this case the orchagent will abort. We can not mock that in the test

**Comment by neethajohn** [comment]
Changes look good to me. Not approving because of the coverage failure.

**Comment by liat-grozovik** [comment]
@prsunny, @neethajohn  please approve to merge as the coverage part is false alarm

**Review by neethajohn — APPROVED** [review]

**Comment by neethajohn** [comment]
Reviewed the PR and unit tests coverage is good. Discussed with @prsunny offline, merging this PR since current diff coverage infrastructure does not take into account unit test coverage

**Pull request merged**
