### PR TITLE
[MultiDB]: using new APIs in orch agents and mock_tests

### PR DESCRIPTION
**Pull request by dzhangalibaba**
* replacing old APIs with new APIs in orch agents
* fix mock_tests cases
  * adding database_config.json
  * adding mock DBConnector(X, X)
  * using new APIs in mock_tests

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
@qiluo-msft BTW for this PR, we need the latest vs docker image to pass vs tests. https://github.com/Azure/sonic-buildimage/pull/3757

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by dzhangalibaba** [comment]
Thanks for reviewing. 
FYI, I ran vs tests passed on local. Looks swss build on Jenkis failed for a while recently. Any reason ?
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build/


  

> Looks good to me. Make sure vs test pass.

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
one question， the vs tests looks having some issues itself. I run "retest this please" many times, every time , it report different failure cases. If we check two vs tests together, then all test cases are passed.  Looks to pass vs tests needs luck ???

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
retest this please

**Comment by dzhangalibaba** [comment]
after several tries,  vs tests passed. @qiluo-msft

**Pull request merged**
