### PR TITLE
[mclagsyncd] fix out of order initialization

### PR DESCRIPTION
**Pull request by novikauanton**
**What I did**

Reorder class member variables.

**Why I did it**

I've encountered an issue with m_bufSize, it's initialization is random, some times it may be initializied with 0, some times with random value.

`m_bufSize` use `MSG_BATCH_SIZE` for initialization:

```
MclagLink::MclagLink(Select *select, int port) :
    MSG_BATCH_SIZE(256),
    m_bufSize(MCLAG_MAX_MSG_LEN * MSG_BATCH_SIZE),
    ...
```

but `MSG_BATCH_SIZE` declared after `m_bufSize`

```
class MclagLink : public Selectable {
  private:
    unsigned int m_bufSize;
    ...
    const int MSG_BATCH_SIZE;
    ...
```

so MSG_BATCH_SIZE will be initialized after m_bufSize, and m_bufSize will use MSG_BATCH_SIZE with uninitialized value.

**How I verified it**

Setup mclag topology, some times mclagsyncd will not be able to receive data after startup.

**Details if related**

[More about this issue in cpp reference](https://en.cppreference.com/w/cpp/language/constructor#Initialization_order)

IMHO it must be treated as compilation error, so it will be better to use`-Werror=reorder` parameter for compiler to avoid such issues.

### CODE REVIEW

**Comment by novikauanton** [comment]
@gechiang could you please review?

**Review by msosyak — APPROVED** [review]

**Comment by msosyak** [comment]
@prsunny  Could we merge this?

**Comment by gechiang** [comment]
Adding @Praveen-Brcm for visibility and the compilation enabling question.
The changes look good to me.  Once Praveen approves it will merge it.
Thanks!

**Review by gechiang — APPROVED** [review]
LGTM. Let's wait for @Praveen-Brcm approval before I merge this in.

**Comment by msosyak** [comment]
@Praveen-Brcm Have a look, please.

**Review by akokhan — APPROVED** [review]

**Comment by Praveen-Brcm** [comment]
@gechiang , @akokhan @msosyak : sorry to respond late on this. I missed on it.
The changes looks good. Would like to understand if the issue is seen consistently.? We have not see such issue in Broadcom testing.

**Comment by novikauanton** [comment]
@Praveen-Brcm it is undefined behavior, so the issue is not consistent, it is random. The issue could be easily see only when `MSG_BATCH_SIZE = 0` before initialization (depends on previous data on stack). On my setup the issue seen only during first start of mclagsyncd on specific hardware.

**Pull request merged**
