### PR TITLE
[vnet]: Update VNET route table size to 40K for BITMAP implementation

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**What I did**
Updated VNET route table size to 40K for BITMAP implementation
**Why I did it**
Updated it according to latest supported value for BITMAP implementation
**How I verified it**
Configured 40K BITMAP VNET routes and verified they are applied correctly
**Details if related**
N/A

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
retest this please

**Comment by volodymyrsamotiy** [comment]
@prsunny Could you please help to set "bmtor" label for this PR? Just to not forget that it should be cherry-picked once merged.

**Comment by liat-grozovik** [comment]
retest vs please

**Comment by lguohan** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Pull request merged**
