### PR TITLE
Enable C++ unit test during build

### PR DESCRIPTION
**Pull request by qiluo-msft**
TODO
- [x] remove tests from deb package.

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
i am not exactly sure if the those ut tests have been running or not.

make  check-TESTS
make[3]: Entering directory '/sonic/swss/tests'
make[4]: Entering directory '/sonic/swss/tests'
PASS: tests
============================================================================
Testsuite summary for sonic-swss 1.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

**Comment by lguohan** [comment]
thanks for taking care of this!

**Comment by qiluo-msft** [comment]
This is a sample output for a failure case, so the test did run.
```
FAIL: tests
==========================================
   sonic-swss 1.0: tests/test-suite.log
==========================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests
===========

Running main() from gtest_main.cc
[==========] Running 44 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 8 tests from swssnet
[ RUN      ] swssnet.copy1_v6
swssnet_ut.cpp:20: Failure
      Expected: buf
      Which is: "2001:4898:f0:f153:357c:77b2:49c9:627c"
To be equal to: "2001:4898:f0:f153:357c:77b2:49c9:6271"
[  FAILED  ] swssnet.copy1_v6 (0 ms)
[ RUN      ] swssnet.copy1_v4
[       OK ] swssnet.copy1_v4 (0 ms)
[ RUN      ] swssnet.copy2_v6
[       OK ] swssnet.copy2_v6 (0 ms)
[ RUN      ] swssnet.copy2_v4
[       OK ] swssnet.copy2_v4 (0 ms)
[ RUN      ] swssnet.copy3_v6
[       OK ] swssnet.copy3_v6 (0 ms)
[ RUN      ] swssnet.copy3_v4
[       OK ] swssnet.copy3_v4 (0 ms)
[ RUN      ] swssnet.subnet_v6
[       OK ] swssnet.subnet_v6 (0 ms)
[ RUN      ] swssnet.subnet_v4
[       OK ] swssnet.subnet_v4 (0 ms)
[----------] 8 tests from swssnet (0 ms total)

[----------] 36 tests from request_parser
[ RUN      ] request_parser.simpleKey
[       OK ] request_parser.simpleKey (0 ms)
[ RUN      ] request_parser.simpleKeyEmptyAttrs
[       OK ] request_parser.simpleKeyEmptyAttrs (0 ms)
[ RUN      ] request_parser.complexKey
[       OK ] request_parser.complexKey (0 ms)
[ RUN      ] request_parser.deleteOperation1
[       OK ] request_parser.deleteOperation1 (0 ms)
[ RUN      ] request_parser.deleteOperation2
[       OK ] request_parser.deleteOperation2 (0 ms)
[ RUN      ] request_parser.deleteOperationWithAttr
[       OK ] request_parser.deleteOperationWithAttr (0 ms)
[ RUN      ] request_parser.wrongOperation
[       OK ] request_parser.wrongOperation (0 ms)
[ RUN      ] request_parser.wrongkey1
[       OK ] request_parser.wrongkey1 (0 ms)
[ RUN      ] request_parser.wrongkey2
[       OK ] request_parser.wrongkey2 (0 ms)
[ RUN      ] request_parser.wrongkeyType1
[       OK ] request_parser.wrongkeyType1 (0 ms)
[ RUN      ] request_parser.wrongAttributeNotFound
[       OK ] request_parser.wrongAttributeNotFound (0 ms)
[ RUN      ] request_parser.wrongRequiredAttribute
[       OK ] request_parser.wrongRequiredAttribute (0 ms)
[ RUN      ] request_parser.wrongAttrTypeBoolean
[       OK ] request_parser.wrongAttrTypeBoolean (0 ms)
[ RUN      ] request_parser.wrongAttrTypeMac
[       OK ] request_parser.wrongAttrTypeMac (0 ms)
[ RUN      ] request_parser.wrongAttrTypePacketAction
[       OK ] request_parser.wrongAttrTypePacketAction (0 ms)
[ RUN      ] request_parser.wrongAttrTypeVlan_wrong_name
[       OK ] request_parser.wrongAttrTypeVlan_wrong_name (0 ms)
[ RUN      ] request_parser.wrongAttrTypeVlan_out_of_high_bound
[       OK ] request_parser.wrongAttrTypeVlan_out_of_high_bound (0 ms)
[ RUN      ] request_parser.wrongAttrTypeVlan_out_of_low_bound
[       OK ] request_parser.wrongAttrTypeVlan_out_of_low_bound (0 ms)
[ RUN      ] request_parser.wrongAttrTypeVlan_out_of_int_range
[       OK ] request_parser.wrongAttrTypeVlan_out_of_int_range (0 ms)
[ RUN      ] request_parser.wrongAttrTypeVlan_invalid_int
[       OK ] request_parser.wrongAttrTypeVlan_invalid_int (0 ms)
[ RUN      ] request_parser.correctAttrTypePacketAction1
[       OK ] request_parser.correctAttrTypePacketAction1 (0 ms)
[ RUN      ] request_parser.correctAttrTypePacketAction2
[       OK ] request_parser.correctAttrTypePacketAction2 (0 ms)
[ RUN      ] request_parser.emptyAttrValue1
[       OK ] request_parser.emptyAttrValue1 (0 ms)
[ RUN      ] request_parser.correctAttrTypePacketAction3
[       OK ] request_parser.correctAttrTypePacketAction3 (0 ms)
[ RUN      ] request_parser.correctParseAndClear
[       OK ] request_parser.correctParseAndClear (0 ms)
[ RUN      ] request_parser.incorrectParseAndClear
[       OK ] request_parser.incorrectParseAndClear (0 ms)
[ RUN      ] request_parser.correctClear
[       OK ] request_parser.correctClear (0 ms)
[ RUN      ] request_parser.anotherKeySeparator
[       OK ] request_parser.anotherKeySeparator (0 ms)
[ RUN      ] request_parser.notDefinedAttrType
[       OK ] request_parser.notDefinedAttrType (0 ms)
[ RUN      ] request_parser.notDefinedKeyType
[       OK ] request_parser.notDefinedKeyType (0 ms)
[ RUN      ] request_parser.uint_and_ip_keys
[       OK ] request_parser.uint_and_ip_keys (0 ms)
[ RUN      ] request_parser.wrong_ip_key
[       OK ] request_parser.wrong_ip_key (0 ms)
[ RUN      ] request_parser.wrong_uint_key_1
[       OK ] request_parser.wrong_uint_key_1 (0 ms)
[ RUN      ] request_parser.wrong_uint_key_2
[       OK ] request_parser.wrong_uint_key_2 (0 ms)
[ RUN      ] request_parser.prefix_key1
[       OK ] request_parser.prefix_key1 (0 ms)
[ RUN      ] request_parser.wrong_key_ip_prefix
[       OK ] request_parser.wrong_key_ip_prefix (0 ms)
[----------] 36 tests from request_parser (1 ms total)

[----------] Global test environment tear-down
[==========] 44 tests from 2 test cases ran. (1 ms total)
[  PASSED  ] 43 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] swssnet.copy1_v6

 1 FAILED TEST
FAIL tests (exit status: 1)

============================================================================
Testsuite summary for sonic-swss 1.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
```

**Pull request merged**
