### PR TITLE
[VLAN] Add pytest cases to validate different use-case of tagging_mode.

### PR DESCRIPTION
**Pull request by linemma**
**What I did**
Add pytest cases to validate different use-case of tagging_mode.

**Why I did it**

**How I verified it**
Test cases:
1. Input normal configuration to verify that:
  - the configuration shall be succeed
  - the value in asic database shall be expected
2. Input invalid configuration to verify that:
  - the configuration shall be failed
  - the entry shall not existed in asic database
3. Verify default value:
  - the default tagging_mode shall be "untagged"

**Details if related**

Signed-off-by: Emma Lin <emma_lin@edge-core.com>

### CODE REVIEW

**Comment by lguohan** [comment]
@linemma , can you resolve conflict?

**Comment by linemma** [comment]
@lguohan, done. Please review the modification, thanks.

**Comment by linemma** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by linemma** [comment]
retest this please

**Comment by lguohan** [comment]
can you resolve the conflict?

**Comment by linemma** [comment]
@lguohan, resolved, please review. Thanks.

**Comment by lguohan** [comment]
can you do a rebase so that I can see the exact your changes?

**Comment by linemma** [comment]
Sorry, I don't understand. Could you tell me what should I do?

**Comment by linemma** [comment]
@lguohan, I fix some problem at this morning, please review the modification. I will resolve the conflict on #875 after this PR merged. Thanks!

**Pull request merged**
