### PR TITLE
[infmgrd][intforch]: Change key format

### PR DESCRIPTION
**Pull request by marian-pritsak**
Possible key permutations:
* INTERFACE_NAME
* INTERFACE_NAME|VRF(VNET)_NAME
* INTERFACE_NAME|IP_PREFIX
* INTERFACE_NAME|VRF(VNET)_NAME|IP_PREFIX

Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
retest this please

**Comment by marian-pritsak** [comment]
@prsunny 
Logs are strange:
```
Step 67/85 : COPY python-debs/python-sonic-utilities_1.2-1_all.deb /debs/
COPY failed: stat /data/docker/tmp/docker-builder211509833/python-debs/python-sonic-utilities_1.2-1_all.deb: no such file or directory
Build step 'Execute shell' marked build as failure
```

Why it might be missing?

**Comment by lguohan** [comment]
retest this please

**Comment by marian-pritsak** [comment]
retest this please

**Comment by liat-grozovik** [comment]
@lguohan and @prsunny could you please review? is this enhancement seems correct? if so, VS will be fixed before merge .

**Comment by prsunny** [comment]
@liat-grozovik , @marian-pritsak , we have identified some concerns with this in the IP address delete flow and would like to take the design for further discussion

**Comment by marian-pritsak** [comment]
Not applicable. Closing.

**Pull request closed without merging**
