### PR TITLE
neighsyncd: Ignoring IPv6 link-local addresses for now as are not used

### PR DESCRIPTION
**Pull request by stcheng**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
If not ignored, what is the harm?

**Comment by stcheng** [comment]
there shall be no harm if ignored. the reason to ignore it here is to prevent the issue that same IP/MAC pair appears on different ports on the same switch. this will be fixed later with some major code changes.

**Comment by qiluo-msft** [comment]
Thanks! You mean "there shall be no harm if **NOT** ignored"?

**Comment by stcheng** [comment]
if not ignored, the current code cannot solve the same IP/MAC pair appears on different ports issue. that's the harm. will be fixed.

**Pull request merged**
