### PR TITLE
[dvs] Refactor NAT tests to use redis polling fixtures

### PR DESCRIPTION
**Pull request by daall**
Signed-off-by: Danny Allen <daall@microsoft.com>

**What I did**
I refactored the NAT tests to use the redis polling fixtures added by #1213.

**Why I did it**
The NAT tests are failing intermittently due to timing issues, which is blocking PR builds.

**How I verified it**
```
daall@rainier:~/dev/sonic-swss/tests$ sudo pytest -s -vv --dvsname=vs test_nat.py
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/daall/dev/sonic-swss/tests
plugins: flaky-3.6.1
collected 10 items                                                                                                                                                                                         

test_nat.py::TestNat::test_NatGlobalTable PASSED
test_nat.py::TestNat::test_NatInterfaceZone PASSED
test_nat.py::TestNat::test_AddNatStaticEntry PASSED
test_nat.py::TestNat::test_DelNatStaticEntry PASSED
test_nat.py::TestNat::test_AddNaPtStaticEntry PASSED
test_nat.py::TestNat::test_DelNaPtStaticEntry PASSED
test_nat.py::TestNat::test_AddTwiceNatEntry PASSED
test_nat.py::TestNat::test_DelTwiceNatStaticEntry PASSED
test_nat.py::TestNat::test_AddTwiceNaPtEntry PASSED
test_nat.py::TestNat::test_DelTwiceNaPtStaticEntry PASSED

======================================================================================== 10 passed in 53.86 seconds ========================================================================================
```

**Details if related**
Pre-refactor test results: 8/10 test runs passed, 52s average
Post-refactor test results: 10/10 test runs passed, 52s average

### CODE REVIEW

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
depends on Azure/sonic-buildimage#4259

**Comment by lguohan** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Pull request merged**
