### PR TITLE
[Reclaim buffer][202106] Common code update

### PR DESCRIPTION
**Pull request by stephenxs**
This is to backport #1996 to 202106.

**What I did**
Common code update for reclaiming buffer.

1. Loading zero_profiles when dynamic buffer manager starting
    The buffer manager won't consume it for now. This is to pass Azure CI.
2. Support removing a buffer pool.
3. Support exposing maximum PGs and queues per port
4. Support transmit between bitmap and map string
5. Change the log severity from `ERROR` to `NOTICE` when parsing buffer profile from buffer profile list failed. Typically this can be resolved by retrying.
    The severity of similar log when parsing buffer PG and queue is already `NOTICE`.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**

To split large PR into smaller ones and help pass CI.

**How I verified it**

vs test and regression test.

**Details if related**

### CODE REVIEW

**Comment by stephenxs** [comment]
Checker failed due to Unable to fetch sonic swss common deb

**Review by neethajohn — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@stephenxs  can you please check why LGTM is failing?

**Comment by stephenxs** [comment]
> @stephenxs can you please check why LGTM is failing?

@liat-grozovik 202106 LGTM failed because PR #2035 hasn't been cherry-picked to 202106. 
The build failures are due to the error `##[error]The container 10691031 could not be found.`

**Comment by stephenxs** [comment]
LGTM failed due to 
```
[2021-12-08 08:11:53] [build-stdout] g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I flex_counter -I debug_counter -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/libnl3 -I/usr/include/swss -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-switch-default -Wno-long-long -Wno-redundant-decls -I /usr/include/sai -I/opt/work/lgtm-workspace/usr/include -I/opt/work/lgtm-workspace/usr/include/swss -I/opt/work/lgtm-workspace/usr/include/sai  -g -O2 -MT orchagent-main.o -MD -MP -MF .deps/orchagent-main.Tpo -c -o orchagent-main.o `test -f 'main.cpp' || echo './'`main.cpp
[2021-12-08 08:11:53] [build-stderr] main.cpp:2:10: fatal error: sai.h: No such file or directory
[2021-12-08 08:11:53] [build-stderr]     2 | #include "sai.h"
[2021-12-08 08:11:53] [build-stderr]       |          ^~~~~~~
[2021-12-08 08:11:53] [build-stderr] compilation terminated.
[2021-12-08 08:11:53] [build-stderr] make[2]: *** [Makefile:644: orchagent-main.o] Error 1
[2021-12-08 08:11:53] [build-stdout] make[2]: Leaving directory '/opt/src/orchagent'
```
Looks like we still have issues in 202106 building environment.

**Comment by stephenxs** [comment]
With LGTM using 202106 branch of swss-common and sairedis, LGTM build merge passed.
Will open another PR to fix the LGTM and revert it in this PR.

**Comment by stephenxs** [comment]
LGTM depends on PR #2074.

**Comment by stephenxs** [comment]
Currently, the PR depends on #2118 for the vstest failure.

**Comment by stephenxs** [comment]
LGTM failure: looks like the same as that on master.
```
[2022-02-25 05:58:24] [build-stdout] [92mProcessing saivlan_8h.xml[0m
[2022-02-25 05:58:24] [build-stdout] [92mProcessing saiwred_8h.xml[0m
[2022-02-25 05:58:24] [build-stdout] [91mERROR: invalid type '' for SAI_ACL_COUNTER_ATTR_TABLE_ID[0m
[2022-02-25 05:58:24] [build-stdout] [91mERROR: flags are not defined for SAI_ACL_COUNTER_ATTR_TABLE_ID[0m
[2022-02-25 05:58:24] [build-stdout] [91mERROR: FATAL ERROR === MUST FIX === : Can't use an undefined value as an ARRAY reference at parse.pl line 1464.
[2022-02-25 05:58:24] [build-stdout] [0m
[2022-02-25 05:58:24] [build-stderr] make[3]: *** [Makefile:102: saimetadata.h] Error 1
[2022-02-25 05:58:24] [build-stdout] make[3]: Leaving directory '/opt/src/sonic-sairedis/SAI/meta'
[2022-02-25 05:58:24] [build-stderr] make[2]: *** [Makefile:1354: saimeta-gen] Error 2
[2022-02-25 05:58:24] [build-stdout] make[2]: Leaving directory '/opt/src/sonic-sairedis/meta'
[2022-02-25 05:58:24] [build-stderr] make[1]: *** [Makefile:433: install-recursive] Error 1
[2022-02-25 05:58:24] [build-stdout] make[1]: Leaving directory '/opt/src/sonic-sairedis'
[2022-02-25 05:58:24] [build-stderr] dh_auto_install: error: make -j1 install DESTDIR=/opt/src/sonic-sairedis/debian/tmp AM_UPDATE_INFO_DIR=no returned exit code 2
[2022-02-25 05:58:24] [build-stderr] make: *** [debian/rules:59: binary-syncd-vs] Error 25
```

**Pull request closed without merging**
