### PR TITLE
Enable a VLAN test case for VS platform

### PR DESCRIPTION
**Pull request by vasant17**
**What I did**
Enabled test_MultipleVlan test case in test_vlan.py. 

**Why I did it**

**How I verified it**
Ran the test case in VS container
```
vapatil@server09:~/workspace/DPB/sonic-buildimage/src/sonic-swss/tests$ sudo pytest --pdb -s -v --dvsname=vs-vp test_vlan.py -k test_MultipleVlan
[sudo] password for vapatil: 
======================================================================= test session starts ========================================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.0, py-1.8.0, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: /home/vapatil/workspace/DPB/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 25 items                                                                                                                                                 

test_vlan.py::TestVlan::test_MultipleVlan remove extra link dummy
remove extra link Vlan100@Bridge
remove extra link Vlan101@Bridge
remove extra link Vlan102@Bridge
remove extra link Vlan103@Bridge
remove extra link Vlan104@Bridge
remove extra link Vlan105@Bridge
remove extra link Vlan106@Bridge
remove extra link Vlan107@Bridge
remove extra link Vlan108@Bridge
remove extra link Vlan109@Bridge
-----rc=1 for cmd ['sh', '-c', 'ip link show Ethernet20 | grep -w master']-----

-----
-----rc=1 for cmd ['sh', '-c', 'ip link show Ethernet24 | grep -w master']-----

-----
-----rc=1 for cmd ['sh', '-c', 'ip link show Ethernet28 | grep -w master']-----

-----
PASSED                                                                                                             [100%]

======================================================================= 24 tests deselected ========================================================================
============================================================= 1 passed, 24 deselected in 72.37 seconds =============================================================
```
**Details if related**

### CODE REVIEW

**Comment by lguohan** [comment]
vs test failing, can you check?

**Comment by vasant17** [comment]
Sure.

**Comment by vasant17** [comment]
> vs test failing, can you check?

I tried multiple ways to reproduce this. But unable to do so. In-fact I took the image from build-artifact of this PR and checked-out azure/sonic-buildimage. Ran just the test_vlan.py and also tried by running all test cases. Never hit the issue. Will get back to this again after sometime.

**Comment by vasant17** [comment]
retest this please

**Comment by daall** [comment]
Fixed in #1241.

**Pull request closed without merging**
