### PR TITLE
[vstest]: various vstest fixes and enhancements

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <gulv@microsoft.com>

**What I did**
various vstest improvement
* 8620a51 2018-10-22 | [vstest]: disable ipv6 in test_crm.py::test_CrmFdbEntry [Guohan Lu]
* f684d65 2018-10-21 | change mode to 644 for test_setro.py [Guohan Lu]
* 51e0d40 2018-10-22 | Enable aclfield.data for SAI_DTEL_ATTR_INT_L4_DSCP [Guohan Lu]
* 9290950 2018-10-21 | use unique directory to mount redis.sock [Guohan Lu]
* 7d1b09e 2018-10-21 | add --keeptb option to keep testbed after test [Guohan Lu]
* 6ee779c 2018-10-22 | gather logs from vs container [Guohan Lu]
* 9b49555 2018-10-21 | make sure delete the srv namespace after test [Guohan Lu]
* e04bd2d 2018-10-20 | add testlog for all tests [Guohan Lu]
* a2d9be4 2018-10-20 | simplify start_swss/stop_swss [Guohan Lu]
* d76a560 2018-10-21 | add ingore object type to CountSubscribedObjects [Guohan Lu]
* 5e2c1de 2018-10-20 | refactor test_swss_neighbor_syncup test [Guohan Lu]
* 9e9a553 2018-10-20 | ensure vrfmgrd, teammgrd, portmgrd are running before test [Guohan Lu]

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Why change so many sleep?

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
