### PR TITLE
[dvs] Mark unstable tests as xfail

### PR DESCRIPTION
**Pull request by daall**
Signed-off-by: Danny Allen <daall@microsoft.com>

**Motivation**
I marked three tests that are consistently flaky as `xfail` so that they do not block PRs. Following up with the test authors to get them stabilized in the meantime.

### CODE REVIEW

**Comment by lguohan** [comment]
test issues?

**Comment by daall** [comment]
> test issues?

Yep, fixed!

**Comment by lguohan** [comment]
looks like still some issue.

**Comment by daall** [comment]
> looks like still some issue.

forgot that "reason" was a named arg, whoops

**Comment by daall** [comment]
retest this please

**Pull request merged**
