### PR TITLE
[vnet]: Fix double route installation for BITMAP VNET interface

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

**What I did**
Fixed double route installation for BITMAP VNET interface
**Why I did it**
Removed logic to add/remove subnet route for VNET interface in BITMAP orchagent since now routes should be added/removed by ```routeorch```.
**How I verified it**
Ran VNET ansible test
**Details if related**
N/A

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Right now the route orch installs routes using sai_route_api, not sai_bitmap_router_api. For the VNET interfaces, it must remain with sai_bitmap_router_api.

**Comment by prsunny** [comment]
This is dependent on PR https://github.com/Azure/sonic-swss/pull/943. To be merged after #943 is merged

**Comment by liat-grozovik** [comment]
retest this please

**Comment by prsunny** [comment]
@volodymyrsamotiy , can you check it VS test failure? Its `test_vnet_bitmap` related

**Pull request merged**
