### PR TITLE
Cleanup configure.ac from BFN specific code

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

**What I did**
Removed BFN specific code from configure.ac

**Why I did it**
Migration from libswitchsai to libsai

**How I verified it**
Private build of BFN target

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan please merge this

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest vs please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by prsunny** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Pull request merged**
