### PR TITLE
Create ACL table fails due to incorrect check for supported ACL actions

### PR DESCRIPTION
**Pull request by rck-innovium**
Create ACL table fails due to incorrect check for supported ACL actions #11235

Fixes https://github.com/Azure/sonic-buildimage/issues/11235

Signed-off-by: rck-innovium <rck@innovium.com>

**What I did**
Fixed error https://github.com/Azure/sonic-buildimage/issues/11235

**Why I did it**

Egress ACL table creation was failing.

root@sonic-dut:~#config acl add table DATA_EGRESS_IPV4_TEST L3 -s egress

Error:
Jun 23 02:23:09.467384 sonic-dut ERR swss#orchagent: :- validate: Action SAI_ACL_ACTION_TYPE_REDIRECT is not supported on table DATA_EGRESS_IPV4_TEST
Jun 23 02:23:09.467384 sonic-dut ERR swss#orchagent: :- doAclTableTask: Failed to create ACL table DATA_EGRESS_IPV4_TEST, invalid configur

**How I verified it**

root@sonic-dut:~#config acl add table DATA_EGRESS_IPV4_TEST L3 -s egress

Jun 23 20:49:22.050411 sonic-dut INFO caclmgrd[1278536]: ACL change detected for namespace ''
Jun 23 20:49:22.050473 sonic-dut NOTICE swss#orchagent: :- doAclTableTask: Successfully updated existing ACL table DATA_EGRESS_IPV4_TEST
Jun 23 20:49:22.050546 sonic-dut INFO caclmgrd[1278536]: Spawning ACL update thread for namepsace '' ...
Jun 23 20:49:22.551196 sonic-dut INFO caclmgrd[1278536]: ACL config for namespace '' has not changed for 0.5 seconds. Applying updates ...

```
root@sonic-dut:~# show acl table DATA_EGRESS_IPV4_TEST
Name                   Type    Binding      Description            Stage
---------------------  ------  -----------  ---------------------  -------
DATA_EGRESS_IPV4_TEST  L3      Ethernet0    DATA_EGRESS_IPV4_TEST  egress
                               Ethernet8
                               Ethernet16
                               Ethernet24
                               Ethernet32
                               Ethernet40
                               Ethernet48
                               Ethernet56
                               Ethernet64
                               Ethernet72
                               Ethernet80
                               Ethernet88
                               Ethernet96
                               Ethernet104
                               Ethernet112
                               Ethernet120
                               Ethernet128
                               Ethernet136
                               Ethernet144
                               Ethernet152
                               Ethernet160
                               Ethernet168
                               Ethernet176
                               Ethernet184
                               Ethernet192
                               Ethernet200
                               Ethernet208
                               Ethernet216
                               Ethernet224
                               Ethernet232
                               Ethernet240
                               Ethernet248
root@sonic-dut:~#
```
**Details if related**

### CODE REVIEW

**Review by bingwang-ms — APPROVED** [review]

**Comment by rck-innovium** [comment]
@bingwang-ms  @prsunny 

Please help in backporting to 202111.
We are not able to create ACL tables on few platforms after the below commit.

```
commit bb0733aa67ffc4e430e70bcf2db2dc6316172b32
Author: Stepan Blyshchak <38952541+stepanblyschak@users.noreply.github.com>
Date:   Tue Nov 23 04:32:49 2021 +0200

    [aclorch] Add ACL_TABLE_TYPE configuration  (#1982)

    * [aclorch] Add ACL_TABLE_TYPE configuration
```

 **Please kindly backport the below 2 pull requests to sonic 202111 branch.** 

```
commit 910bfd4d17782a059daf2d81deb87673ae6ca58e
Author: bingwang-ms <66248323+bingwang-ms@users.noreply.github.com>
Date:   Sat May 28 03:04:14 2022 +0800
 
    [ACL] Add default action_list for default ACL table type (#2298)

```

```
commit 1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f
Author: Ravindranath C K <rck@innovium.com>
Date:   Fri Jun 24 20:20:52 2022 +0530

    Create ACL table fails due to incorrect check for supported ACL actions #11235 (#2351)

    Signed-off-by: rck-innovium <rck@innovium.com>
```

**Comment by rck-innovium** [comment]
> @bingwang-ms @prsunny
> 
> Please help in backporting to 202111. We are not able to create ACL tables on few platforms after the below commit.
> 
> ```
> commit bb0733aa67ffc4e430e70bcf2db2dc6316172b32
> Author: Stepan Blyshchak <38952541+stepanblyschak@users.noreply.github.com>
> Date:   Tue Nov 23 04:32:49 2021 +0200
> 
>     [aclorch] Add ACL_TABLE_TYPE configuration  (#1982)
> 
>     * [aclorch] Add ACL_TABLE_TYPE configuration
> ```
> 
> **Please kindly backport the below 2 pull requests to sonic 202111 branch.**
> 
> ```
> commit 910bfd4d17782a059daf2d81deb87673ae6ca58e
> Author: bingwang-ms <66248323+bingwang-ms@users.noreply.github.com>
> Date:   Sat May 28 03:04:14 2022 +0800
>  
>     [ACL] Add default action_list for default ACL table type (#2298)
> ```
> 
> ```
> commit 1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f
> Author: Ravindranath C K <rck@innovium.com>
> Date:   Fri Jun 24 20:20:52 2022 +0530
> 
>     Create ACL table fails due to incorrect check for supported ACL actions #11235 (#2351)
> 
>     Signed-off-by: rck-innovium <rck@innovium.com>
> ```

@prsunny 

Can you please help backport or let us know if I can do something to get this backported.. This is blocking our basic 202111 ACL features..

**Comment by prsunny** [comment]
This is already labeled for 202111. @judyjoseph , can you please help with cherry-pick?

**Comment by kishoreatreya** [comment]
@judyjoseph could you help cherry-pick this to 202111? This has been pending for sometime.

**Comment by judyjoseph** [comment]
@rck-innovium @kishoreatreya Sorry for delay - Can you check if this PR is applicable in 202111 branch as I see the fix is in AclTable::addMandatoryActions() - and the function is not present in the 202111 codebase.

**Comment by rck-innovium** [comment]
> @rck-innovium @kishoreatreya Sorry for delay - Can you check if this PR is applicable in 202111 branch as I see the fix is in AclTable::addMandatoryActions() - and the function is not present in the 202111 codebase.

Hi @judyjoseph 

Thanks for looking at this. This PR is applicable for 202111.  
The reason is:

1) There was a commit to **202111 and master ** that breaks ACL table creation on some platforms. Refer commit bb0733aa67ffc4e430e70bcf2db2dc6316172b32

2) A fix for this was made in **master**. Refer commit 910bfd4d17782a059daf2d81deb87673ae6ca58e

3) The current PR (#2351) was made to fix a bug in the above commit it in **master**. Refer commit 1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f


So, the sequence of backporting required is:

1. Backport#1 commit 910bfd4d17782a059daf2d81deb87673ae6ca58e

2. Backport#2 commit 1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f


This has been detailed in an earlier comment here:
https://github.com/sonic-net/sonic-swss/pull/2351#issuecomment-1211820441

**Comment by judyjoseph** [comment]
> > @rck-innovium @kishoreatreya Sorry for delay - Can you check if this PR is applicable in 202111 branch as I see the fix is in AclTable::addMandatoryActions() - and the function is not present in the 202111 codebase.
> 
> Hi @judyjoseph
> 
> Thanks for looking at this. This PR is applicable for 202111. The reason is:
> 
> 1. There was a commit to **202111 and master ** that breaks ACL table creation on some platforms. Refer commit [bb0733a](https://github.com/sonic-net/sonic-swss/commit/bb0733aa67ffc4e430e70bcf2db2dc6316172b32)
> 2. A fix for this was made in **master**. Refer commit [910bfd4](https://github.com/sonic-net/sonic-swss/commit/910bfd4d17782a059daf2d81deb87673ae6ca58e)
> 3. The current PR ([Create ACL table fails due to incorrect check for supported ACL actions #2351](https://github.com/sonic-net/sonic-swss/pull/2351)) was made to fix a bug in the above commit it in **master**. Refer commit [1b8bd94](https://github.com/sonic-net/sonic-swss/commit/1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f)
> 
> So, the sequence of backporting required is:
> 
> 1. Backport#1 commit [910bfd4](https://github.com/sonic-net/sonic-swss/commit/910bfd4d17782a059daf2d81deb87673ae6ca58e)
> 2. Backport#2 commit [1b8bd94](https://github.com/sonic-net/sonic-swss/commit/1b8bd94ef7e44f6089fc12efd456a3caa7aafd3f)
> 
> This has been detailed in an earlier comment here: [#2351 (comment)](https://github.com/sonic-net/sonic-swss/pull/2351#issuecomment-1211820441)

raised a cherry-pick PR https://github.com/sonic-net/sonic-swss/pull/2497

**Comment by judyjoseph** [comment]
Update sonic-swss submodule: https://github.com/sonic-net/sonic-buildimage/pull/12521

**Pull request merged**
