### PR TITLE
mv WarmStart class from swss to swss-common repo

### PR DESCRIPTION
**Pull request by jipanyang**
Signed-off-by: Jipan Yang <jipan.yang@alibaba-inc.com>

**What I did**
Move WarmStart class from swss to swss-common repo

**Why I did it**

WarmStart class is to be used beyond swss repo

**How I verified it**
VS test.

Note: it has dependency on https://github.com/Azure/sonic-swss-common/pull/241

**Details if related**

### CODE REVIEW

**Comment by yxieca** [comment]
I didn't see code change to include warm-restart.h from the new common path. Will this create problem?

**Comment by jipanyang** [comment]
@yxieca Since we didn't change the header file name, and they will be available in swss-common library, no code change to include warm-restart.h is needed.

**Comment by yxieca** [comment]
retest this please

**Comment by yxieca** [comment]
retest this please

**Pull request merged**
