### PR TITLE
[vstest] Increase VS test timeout

### PR DESCRIPTION
**Pull request by dgsudharsan**
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>

**What I did**
Increased VS test timeout to 480 seconds and cherrypick of https://github.com/Azure/sonic-swss/pull/2309

**Why I did it**
Align with timeout in master and to avoid timeouts in other PRs

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
If cherry-pick is delayed, you can update this PR with the WB fix.

**Comment by liat-grozovik** [comment]
@dgsudharsan  do we still need this PR? if so, i will signoff.

**Comment by dgsudharsan** [comment]
> @dgsudharsan do we still need this PR? if so, i will signoff.

I have synced to the latest and will check if there aren't any timeouts. If no timeouts we can drop this PR

**Pull request closed without merging**
