### PR TITLE
Update nat entries to use nat_type to support DNAT Pool changes.

### PR DESCRIPTION
**Pull request by AkhileshSamineni**
Code changes:

NatMgr:

Setting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when first Static NAT/NAPT entry is added at config_db.
Incrementing the ref count in "m_natDnatPoolInfo" for same destination-ip for next Static NAT/NAPT entry is added at config_db.
Decrementing the reference count in "m_natDnatPoolInfo" for same destination-ip when Static NAT/NAPT entry is deleted at config_db.
Deleting the "APP_NAT_DNAT_POOL_TABLE_NAME" table with destination-ip when last Static NAT/NAPT entry is deleted at config_db.
It does the same for all IP-Addresses from pool-addresses range in NAT Pool configuration in config_db.

NatOrch:

Creating DNAT_POOL entries using nat_type as "SAI_NAT_TYPE_DESTINATION_NAT_POOL" when "APP_NAT_DNAT_POOL_TABLE_NAME" table is created.
Deleting DNAT_POOL entries using nat_type as "SAI_NAT_TYPE_DESTINATION_NAT_POOL" when "APP_NAT_DNAT_POOL_TABLE_NAME" table is deleted.
Updated code to use nat_type while creating the nat entries.

Depends on :
https://github.com/Azure/sonic-utilities/pull/1001
https://github.com/Azure/sonic-swss-common/pull/367
https://github.com/Azure/sonic-sairedis/pull/644

Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
@arlakshm @rlhui Need to update sonic-swss-common submodule. For successful compilation of this PR, it need PR https://github.com/Azure/sonic-swss-common/pull/367 changes.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
retest this please.

**Comment by AkhileshSamineni** [comment]
@arlakshm @prsunny How to restart the "LGTM analysis : C/C++" again, "Retest this please" is not triggering it.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Review by arlakshm — APPROVED** [review]
Lgtm

**Comment by arlakshm** [comment]
retest this please

**Comment by AkhileshSamineni** [comment]
retest this please

**Comment by AkhileshSamineni** [comment]
@arlakshm Please merge this PR.

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
