### PR TITLE
[Dryrun] Use 202106 branches in azure pipeline

### PR DESCRIPTION
**Pull request by stephenxs**
Signed-off-by: stephens <stephens@contoso.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@stephenxs, FYI I closed this PR as now 202106 swss checkers are passing.

**Comment by stephenxs** [comment]
> @stephenxs, FYI I closed this PR as now 202106 swss checkers are passing.

Looks like they are still failing due to the same issue?

**Pull request closed without merging**
