### PR TITLE
[restore_neighbors] python3 support for restore_neighbors.py

### PR DESCRIPTION
**Pull request by zhenggen-xu**
[restore_neighbors] python3 support for restore_neighbors.py

Signed-off-by: Zhenggen Xu <zxu@linkedin.com>

This is dependent on https://github.com/Azure/sonic-buildimage/pull/6207

**What I did**
Change the restore_neighbors.py to support python3

**Why I did it**
python2 EOL.

**How I verified it**
swss vs tests

**Details if related**

### CODE REVIEW

**Comment by jleveque** [comment]
I believe the vs test will fail until the next vs image is built later today with the changes from https://github.com/Azure/sonic-buildimage/pull/6207. Will wait to retest until tomorrow.

**Comment by zhenggen-xu** [comment]
retest this please

**Comment by zhenggen-xu** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by zhenggen-xu** [comment]
retest this please

**Comment by lguohan** [comment]
retest vs please

**Comment by lguohan** [comment]
retest this please

**Comment by zhenggen-xu** [comment]
retest this please

**Review by lguohan — APPROVED** [review]

**Pull request merged**
