### PR TITLE
[ci][202106] Use correct branch when downloading artifact.

### PR DESCRIPTION
**Pull request by liushilongbuaa**
**What I did**
Cherry-pick some pipeline related PRs:
https://github.com/Azure/sonic-swss/commit/4d6fa42ab97c236d54ce4d36e884ec3e224e65c2 [ci] Change artifact reference pipeline to common lib pipeline. (https://github.com/Azure/sonic-swss/pull/2294)
https://github.com/Azure/sonic-swss/commit/d7b5ff79907b22ed13a120d599eaf7c1ad8b6837 [ci] Use correct branch when downloading artifact. (https://github.com/Azure/sonic-swss/pull/2292)
https://github.com/Azure/sonic-swss/commit/2f1324473001e9fd26c2ed7bbb92fb387732a0d0 [ci] Improve azp trigger settings to automaticlly support new release branch. (https://github.com/Azure/sonic-swss/pull/2289)
**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by liushilongbuaa** [comment]
Hi @prsunny  , 202106 branch has some failure test cases. PR validation will never pass. Can you help fix them?

**Review by xumia — APPROVED** [review]

**Comment by prsunny** [comment]
Looks like there are build failures.

**Comment by liushilongbuaa** [comment]
> Looks like there are build failures.

Because swss-common 202106 branch didn't have successful build. https://dev.azure.com/mssonic/build/_build/results?buildId=112086&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=f9db2383-9349-50ba-61c3-4bde15cec59e
When these 28 failure UT cases are fixed, failures will be fixed.

**Comment by liushilongbuaa** [comment]
Hi @prsunny , 202106 branch is still unhealthy.
About 27 test cases are continuously failing.
https://dev.azure.com/mssonic/build/_build/results?buildId=114813&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=f9db2383-9349-50ba-61c3-4bde15cec59e

**Pull request merged**
