### PR TITLE
Add initial value for weight in overlay nexthops

### PR DESCRIPTION
**Pull request by shi-su**
**What I did**
Add initial value for weight in overlay nexthops.

**Why I did it**
Without initializing the weight variable, it may be initialized as non-zero values. This PR aims to prevent it from happening.

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@shi-su should this PR goes to 202111? if so, can you please add the proper label?

**Pull request merged**
