### PR TITLE
[vxlan test]: Disable vxlan test

### PR DESCRIPTION
**Pull request by pavel-shirshov**
**What I did**
Disable vxlan test
**Why I did it**
The test is failing, but I can't reproduce it on my local machine. I got:
I disable it until I found the reason why the CI test fail
```
pavelsh@pavelsh-vm:/mnt/sonic-buildimage/src/sonic-swss/tests$ sudo pytest -v test_vxlan_tunnel.py      ========================================= test session starts ==========================================
platform linux2 -- Python 2.7.12, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: /mnt/sonic-buildimage/src/sonic-swss/tests, inifile:
collected 1 item                                                                                       

test_vxlan_tunnel.py::test_vxlan_term_orch PASSED  
```
**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by qiluo-msft** [comment]
Closed, in favor for https://github.com/Azure/sonic-swss/pull/617

**Pull request closed without merging**
