### PR TITLE
Init OrchDaemon with optional warm starting

### PR DESCRIPTION
**Pull request by qiluo-msft**
We don't call syncd_apply_view() at 2 places.

### CODE REVIEW

**Comment by jipanyang** [comment]
Just curious,  are you gonna send apply view signal to syncd after state sync up?

**Comment by qiluo-msft** [comment]
Yes.
This PR doesn't change behaviors and it is a refactoring.

**Comment by jipanyang** [comment]
Current logic is to perform apply view after state restore and before state sync up. With the new change, apply view will be done after state sync up.    I'm not familiar with the latest progress of view comparison solution. Probably that is by design.

Anyway, state sync up is still at TODO status in existing code.  The change here doesn't have real impact, it looks ok to me.

**Comment by qiluo-msft** [comment]
Got your idea. If needed, I will revisit this case after TODO done.

**Pull request merged**
