### PR TITLE
[portsorch]: Use sai_serialize api to write to DB

### PR DESCRIPTION
**Pull request by marian-pritsak**
Keep object IDs serializeable in database,
so that they can be reused later by client code

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Along with https://github.com/Azure/sonic-sairedis/pull/234

**Comment by stcheng** [comment]
could you resolve the conflicts?

**Comment by lguohan** [comment]
can you resolve the conflict.

**Comment by marian-pritsak** [comment]
Done

**Pull request merged**
