### PR TITLE
[mock_tests]: Add CoPP Orch UTs

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**What I did**
* Added `CoPP` UTs

**Why I did it**
* To increase code/feature coverage

**How I verified it**
1. Compile `swss` package

**Details if related**
```
nazariig@c13d94125e90:/sonic/src/sonic-swss/tests/mock_tests$ ./tests --gtest_filter=CoppOrchTest*
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = CoppOrchTest*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from CoppOrchTest
[ RUN      ] CoppOrchTest.TrapGroup_AddRemove
[       OK ] CoppOrchTest.TrapGroup_AddRemove (49 ms)
[ RUN      ] CoppOrchTest.TrapGroupWithPolicer_AddRemove
[       OK ] CoppOrchTest.TrapGroupWithPolicer_AddRemove (45 ms)
[ RUN      ] CoppOrchTest.Trap_AddRemove
[       OK ] CoppOrchTest.Trap_AddRemove (44 ms)
[ RUN      ] CoppOrchTest.TrapWithPolicer_AddRemove
[       OK ] CoppOrchTest.TrapWithPolicer_AddRemove (46 ms)
[----------] 4 tests from CoppOrchTest (184 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (184 ms total)
[  PASSED  ] 4 tests.
```

### CODE REVIEW

**Review by volodymyrsamotiy — DISMISSED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@nazariig , can you please revisit this PR to adopt to existing model? Using similar `setup/teardown` functions. Otherwise it will be inconsistent throughout the mock-tests. Ref PR - https://github.com/Azure/sonic-swss/pull/2266

**Comment by nazariig** [comment]
@prsunny the PR has been approved and merged. Not sure if i understand the concerns here. Different implementations use different amount of initialized Orchs. As long as the compilation works fine and tests are passing, there is no need to align to something. Or if we do want to have something similar across all the tests, i would expect to have some Doc defined.

**Pull request merged**
