### PR TITLE
Fix bug: shellquote the inner string

### PR DESCRIPTION
**Pull request by qiluo-msft**
Fix bug in https://github.com/Azure/sonic-swss/pull/1098#issuecomment-574264500
@banagiri could you please help review?

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest vs please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by banagiri** [comment]
@qiluo-msft , the fix worked, tested on the device.
This can be closed

**Comment by banagiri** [comment]
@qiluo-msft 
Will this be ported to 201911 branch also, as the "inner string" change is also present in 201911 branch also

**Comment by qiluo-msft** [comment]
@banagiri Yes! Requested by a label.

**Pull request merged**
